### ISSUE TITLE
When is the projected release date / GO-LIVE date for the Microsoft.FeatureManagement namespace?

### ISSUE THREAD

**Issue by JBoothUA** [microsoft/FeatureManagement-Dotnet#10]
My organization has an immediate need for this namespace, however we have a restriction that we cannot use anything that is in "PREVIEW" mode.

Can someone tell me or is there a link to information on when this namespace will leave "PREVIEW" and go to the real release 1.0?

Thank you so much!
-Jesse Booth

**Comment by JBoothUA** [comment]
@Is there a better venue to ask this question?

**Comment by jimmyca15** [comment]
@JBoothUA,
By use of the namespace do you mean of this library? There are still a few important aspects of this library that need to be flushed out before the final release (see filed issues). Right now we can't commit to a non-preview date, but it's in the works.

**Comment by zepedrosilva** [comment]
It has been a few months since the last comment (above). Are there any plans for a stable, 1.0 release?

**Comment by lisaguthrie** [comment]
Hi @zepedrosilva, thanks for asking. We are working hard towards a stable 1.0 release, and will announce a specific date this quarter. Stay tuned.

**Comment by zhenlan** [comment]
GA and pricing plan
https://github.com/Azure/AppConfiguration-Announcements/issues/2
