### ISSUE TITLE
Can no longer add multiple custom filters with same name from azure UI

### ISSUE THREAD

**Issue by michaelmcdaniel** [microsoft/FeatureManagement-Dotnet#100]
I'm not sure if this is the correct place to report this, but it's a show stopper for me. (or please point me in the correct direction and close/delete)

I created a custom feature filter to enable features based on claims, aliased as "Claim".  Let's just say it has claim type and value. When I try to add multiple custom filters to the new Azure Feature UI, it no longer allows adding multiples of the same aliased type. 

![ffdup](https://user-images.githubusercontent.com/1678654/95635874-43251880-0a53-11eb-8c7d-488abc8086e7.PNG)

I need to support multiple claim types to target different test groups.  
Am I doing something wrong?  Will this change in a future release to not support this type of workflow?

**Comment by zhenlan** [comment]
@michaelmcdaniel we assumed it's an error when the same filter is added more than once, but apparently, you have a scenario here. I guess your `Claim` feature filter has a parameter and you pass in different values for each instance? If so, does it make sense for your feature filter parameter to accept an array so you don't need the `Claim` feature filter to be declared multiple times?

cc: @MSGaryWang @jiayi11

**Comment by michaelmcdaniel** [comment]
@zhenlan Originally I had a filter that took a dictionary of claim types to match against an array of values.  This worked until I need to map a claim type like `{"http://example/value"=["v1","v2"], "claim-type":"v3" }` which isn't supported due to the colon in the uri key name.  

`public class Settings { ... 
    public IDictionary<string,string[]> Claims { get; set; } 
    ...
}`

This led me to simplify to just having separate filters that defined the Claim Type to an array of values. 

I'm definitely open to other options, but the latest usage was easy.

**Comment by zhenlan** [comment]
@michaelmcdaniel, thanks for sharing the details. For now, you can edit feature flags by using the "Advanced Edit" option in the context menu after right-clicking the feature flag. @jiayi11, I think we should unblock duplicated feature filters from the UI.

BTW, @michaelmcdaniel, the scenario you described sounds like something that can leverage the new "targeting" feature.

**Comment by michaelmcdaniel** [comment]
@zhenlan I believe that is best solution with the least amount of friction.  Thanks for the pointer on the new "targeting" feature.  I will definitely check it out.  Also just wanted to give you all kudos - good stuff!

**Comment by jiayi11** [comment]
I'll work on removing the duplicate filter name checking. I'll update the thread once I have an estimate when it will be deployed. 
@michaelmcdaniel  Currently to workaround this, you can use azure cli [az appconfig feature filter](https://docs.microsoft.com/en-us/cli/azure/appconfig/feature/filter?view=azure-cli-latest) command to update your filter. I can't think of any good suggestions to workaround it on portal,  "Advanced edit" option in context menu also has this name duplication check.

**Comment by jiayi11** [comment]
We are rolling out the fix and it should deployed to all regions before this Friday.

**Comment by michaelmcdaniel** [comment]
certified WOMM.  Thanks everyone!
