### ISSUE TITLE
How do I enable features based on information obtained from HttpContext scoped services?

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/FeatureManagement-Dotnet#103]
If I understand correctly, I need to define a `IFeatureDefinitionProvider` that is request scoped so that I can load the list of enabled features from my database.

Is there any documentation or guidance that can be offered on how I might go about doing this?

**Comment by jimmyca15** [comment]
The [readme](https://github.com/microsoft/FeatureManagement-Dotnet#custom-feature-providers) mentions how to register a custom IFeatureDefinitionProvider. Does your question go beyond just registering the feature definition provider?

**Comment by atrauzzi** [comment]
Yeah, as I wish for the provider to provide a different list of features based on hints from `IHttpContextProvider` and `HttpContext`.

**Comment by jimmyca15** [comment]
The provider can still be a singleton. Are you using ASP.NET Core? If that is the case, you can require `IHttpContextAccessor` in the constructor of your feature definition provider to access the current HttpContext whenever a feature definition is requested.

The pattern that you suggested though sounds interesting. Usually feature definitions are consistent between requests and the dynamic per-HttpContext behavior is implemented in feature filters. Are feature filters something you already evaluated for your purposes?

**Comment by atrauzzi** [comment]
Oh hm... I wonder if you're right and I just misunderstood what Filters are.  I basically want to enable different features based on who is logged in (by getting data from the DB).  I also want to mix this with features from `appsettings.json`, etc...

(My list of _potential_ features still comes purely from code.)

**Comment by jimmyca15** [comment]
The feature definitions are meant to be declarative for the most part. The feature filters reference the properties declared in feature definitions and execute custom logic to see if the current context should result in the feature being on.

The targeting scenario supported by this library is a good demonstration of this. If a feature leverages the targeting feature filter then it will declare the users and groups that have access to the features. That data is part of the feature definition. For a given feature that is using targeting, the targeting feature filter is in charge of reading what users and groups the feature should be enabled for, determining the currently logged in user, and performing the mapping to see if that user is in the allowed set.

**Comment by atrauzzi** [comment]
Okay, so would it make more sense for me to create a Filter that is request-scoped somehow that performs my database access based on currently authenticated etc etc...?

**Comment by jimmyca15** [comment]
Feature Filters are singletons, just like feature definitions provider. My original suggestion of injecting `IHttpContextAccessor` would still apply even if you used a feature filter. Once you inject the context accessor, you'll be able to use the current `HttpContext` inside of the feature filter to dynamically evaluate whether a feature should be on based off two things
* The (mostly) static definition of the feature
  * This is provided through [`FeatureFilterEvaluationContext`](https://github.com/microsoft/FeatureManagement-Dotnet/blob/1a66739bc4f97b503674c7a3b3d4760762efa676/src/Microsoft.FeatureManagement/IFeatureFilter.cs#L18)
* The current executing request

**Comment by atrauzzi** [comment]
I see, are there any potential risks (or even performance drawbacks) of using `IHttpContextAccessor` from a singleton?

**Comment by jimmyca15** [comment]
This is the method promoted by this library. Accessing the HttpContext in a singleton is fine as long as the singleton operates within a request. The pattern could possibly break if the singleton is called in an orphaned task in which there is no request.

**Comment by atrauzzi** [comment]
I see, so the accessor will just look up the correct request along the current thread I guess...

**Comment by jimmyca15** [comment]
Threads are abstracted by Tasks, but essentially yes.

**Comment by jimmyca15** [comment]
Closing as this appears to be answered.

**Comment by atrauzzi** [comment]
It appears as though this design does create some challenges.

 - https://stackoverflow.com/questions/66084757/net-how-do-i-configure-one-of-my-own-scoped-services-to-be-accessed-statically
 - https://mobile.twitter.com/alextrauzzi/status/1358281811579731968

**Comment by jimmyca15** [comment]
The way to retrieve request scoped services would be through [this API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestservices?view=aspnetcore-5.0).

The HttpContext is available through [IHttpContextAccessor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor?view=aspnetcore-5.0).

**Comment by atrauzzi** [comment]
Yeah, that works for now.  Outside of this repo, I'm now curious about how one might make their own `*Accessor` implementation, to avoid having to always go through the `HttpContextAccessor`, etc...

Thanks!
