### ISSUE TITLE
How to read features values which exist in multiple sources?

### ISSUE THREAD

**Issue by efonsecab** [microsoft/FeatureManagement-Dotnet#104]
We need to be able to read specific features enabled/disabled value from multiple places simultaneously, e.g. a feature can be enabled in a database, and disabled in another.
The only possible way to do this I found is to implement a custom class inheriting from FeatureManager, yet I did not find a way in the AddFeatureManagement() configuration to specify a custom class for the IFeatureManager interface.

**Comment by jimmyca15** [comment]
I would expect dynamic evaluation of features to be implemented through the use of `IFeatureFilter`. What is preventing that? If it's the fact that the feature definitions themselves need to be read/registered dynamically, then `IFeatureDefinitionProvider` is also available to implement.

**Comment by jimmyca15** [comment]
Issue hasn't had any updates. Please feel free to ping if there's still any concerns.
