### ISSUE TITLE
Any plans to support .net 5?

### ISSUE THREAD

**Issue by Sergey-Terekhin** [microsoft/FeatureManagement-Dotnet#108]
Hello!
Do you have any plans  to support released .net 5? And if yes, then?
Thank you

**Comment by jimmyca15** [comment]
To clarify the ask here, you just mean to add net5.0 as a target framework of the package right? Or are you experiencing some issues currently?

If that is the ask, I can answer that yes we plan to add net5.0 as a target just as netcoreapp3.1 has been added. The timeline would be early in the new year.

**Comment by jimmyca15** [comment]
This was added in 2.3.0 release.
https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.3.0
