### ISSUE TITLE
Add supports for labels?

### ISSUE THREAD

**Issue by David-Stark** [microsoft/FeatureManagement-Dotnet#110]
Hello!

Wonder if there is any plans to add support for labels? It would be great if we could extend IFeatureManager with a new method of IsEnabledAsync. For example:

_featureManager.IsEnabledAsync("feature", "label"); 

Best regards
David Stark

**Comment by jimmyca15** [comment]
There are no plans to add such an API. Do you mind describing the scenario in which you find such an API to be helpful. We are planning an improvement to the library, and if I'm guessing what you would want to use that API for correctly, then it may help.

**Comment by David-Stark** [comment]
Hello,

I want to be able to target feature flags with a specific label. The label can be a specific user, country or something else. 

For example i have three feature flags that is named awesomeButtonForEditing and they have the label person1, person2, usergroup1 or country1. 

_featureManager.IsEnabledAsync("awesomeButtonForEditing ", "person1");
_featureManager.IsEnabledAsync("awesomeButtonForEditing ", "person2");
_featureManager.IsEnabledAsync("awesomeButtonForEditing ", "usergroup1");
_featureManager.IsEnabledAsync("awesomeButtonForEditing ", "country1");

Now with the SDK i can only toggle on awesomeButtonForEditing and not be able to use the labels in the service. 

Best regads
David Stark

**Comment by jimmyca15** [comment]
Thank you for describing the scenario. This is a common one, and the main way to do it would not be to have multiple feature flags across different labels, but rather to have a single feature flag with parameters.

Feature flags can have [feature filters](https://github.com/microsoft/FeatureManagement-Dotnet#feature-filters) that dynamically enable a feature based off some contextual data. In this case it looks like you have some contextual data about what user is using the app, where they are from, and what groups they are in. This is a perfect use case for a feature filter, and it might fit in perfectly with our built in [targeting filter](https://github.com/microsoft/FeatureManagement-Dotnet#microsofttargeting).

**Comment by David-Stark** [comment]
Big thanks for the explanation !

**Comment by David-Stark** [comment]
After reading the documentation I dont get how i´m suppose to the Target filter to work with a console application? Every example is for ASP.Net Core? 

What i can find is "In console applications there is no ambient context such as HttpContext that feature filters can acquire and utilize to check if a feature should be on or off." 

Is there any more demos/examples how to communicate with the App Config ? And just compare a string value from the "context" ? Should i still use ITargetingContextAccessor ?

**Comment by David-Stark** [comment]
> After reading the documentation I dont get how i´m suppose to use the Target filter to work with a console application? Every example is for ASP.Net Core?
> 
> What i can find is "In console applications there is no ambient context such as HttpContext that feature filters can acquire and utilize to check if a feature should be on or off."
> 
> Is there any more demos/examples how to communicate with the App Config Features with a console applications ? In my case all i need to compare is a string value with the group or user. Do i still use
> ITargetingContextAccessor ?
