### ISSUE TITLE
Examples/demos how to use Microsoft.Targeting with a console application?

### ISSUE THREAD

**Issue by David-Stark** [microsoft/FeatureManagement-Dotnet#111]
After reading the documentation I dont get how i´m suppose to use the Targeting filter to work with a console application? Every example i can find is for ASP.Net Core applications?

What i can find is "In console applications there is no ambient context such as HttpContext that feature filters can acquire and utilize to check if a feature should be on or off."

Is there any more demos/examples how to make this filter to work with a console application ? 

In my case all i need to compare is a string value (context?) with the group or user from what is configured in the Azure Portal and App Configuration Feature. Do i still use ITargetingContextAccessor ?

Best regards 
David Stark

**Comment by jimmyca15** [comment]
Yes, we have this [example app](https://github.com/microsoft/FeatureManagement-Dotnet/tree/main/examples/TargetingConsoleApp).

**Comment by palashjhabak** [comment]
Came to the repo and this issue while searching for something like this in the official documentation on the Microsoft site. Can we edit the official documentation to include this?
