### ISSUE TITLE
A case for synchronous IsEnabled signatures to be provided next to asynchronous ones

### ISSUE THREAD

**Issue by rjgotten** [microsoft/FeatureManagement-Dotnet#120]
Very nice that querying feature flag values async is supported, but the complete removal of synchronous signatures has one big downside: it is no longer possible to use the `IServiceCollection` APIs together with feature flags to inject alternate implementations. 

Something like:

```cs
services.AddScoped<IFooService>(provider =>
{
   var features = provider.GetRequiredService<IFeatureManagerSnapshot>();
   return features.IsEnabled("except-really-inject-bar")
     ? ActivatorUtilities.CreateInstance<BarService>(provider)
     : ActivatorUtilities.CreateInstance<FooService>(provider);
})
```
-- is no longer possible.

Sure, it's possible to write:

```cs
services.AddScoped<IFooService>(provider =>
{
   var features = provider.GetRequiredService<IFeatureManagerSnapshot>();
   return features.IsEnabledAsync("except-really-inject-bar").Result
     ? ActivatorUtilities.CreateInstance<BarService>(provider)
     : ActivatorUtilities.CreateInstance<FooService>(provider);
})
```

-- but that's not really how you should be using async tasks and it's dangerous in the general case.

**Comment by jimmyca15** [comment]
This pattern here would require more than a synchronous signature. The entire feature management pipeline would have to be customized to only use synchronous signatures. I.e. sync feature definition provider and sync feature filters. Is that the desire here?

**Comment by rjgotten** [comment]
The entire thing _used_ to be synchronous, didn't it? It was specifically changed to be asynchronous to facilitate async providers and filters, in the process discarding the sync signatures entirely. Would've been a better idea to have both co-exist; and to optionally wrap a thin layer of `.Result` access around _only_ the individual async providers or filters if you really, _really_ have to and can't avoid it in any other way. (Or have providers and filters implement both a sync and an async interface and use the appropriate one for the type of call, pushing the responsibility further down.)

**Comment by jimmyca15** [comment]
It used to be synchronous. The most feedback we received in preview was to provide an async pipeline for feature evaluation. The async pipeline doesn't prohibit synchronous usage. 

> Would've been a better idea to have both co-exist
That's a lot to juggle as a user of this library. The user would have to know about synchronous and asynchronous evaluation of features. If synchronous evaluation was used, they would have to ensure they didn't use feature providers | feature filters that required asynchronous execution.

I know there is a value of having a fully synchronous pipeline. The tradeoff for complexity of maintaining a fully sync and fully synchronous feature evaluation pipeline wasn't something we were willing to take.

For now, synchronous behavior can be achieved by ensuring that all of the pluggable feature manager services (i.e. IFeatureDefinitionProvider, IFeatureFilter) are completing synchronously. The built-in services do complete synchronously.

**Comment by rjgotten** [comment]
>The built-in services do complete synchronously.

In other words: `IsEnabledAsync("foo").Result` is safe because the task should come out as pre-completed?

**Comment by jimmyca15** [comment]
> In other words: IsEnabledAsync("foo").Result is safe because the task should come out as pre-completed?

That depends on what types are being used to implement the feature management interfaces. If none of the default interface implementations are substituted, and no asynchronous feature filters are used then the pipeline is synchronous. In that case, that snippet would be "safe", meaning it would not block a thread.

Please feel free to re-open if there are any more questions.
