### ISSUE TITLE
TargetFilter only returns positive group evaluation result

### ISSUE THREAD

**Issue by yuanyi2121** [microsoft/FeatureManagement-Dotnet#123]
There is an issue with this line: https://github.com/microsoft/FeatureManagement-Dotnet/blob/df0f9d20db4c0a8f2c5bbb3362db614ff1c50944/src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs#L86

it only returns true when a group evaluation returned true, otherwise it will use the default percentage.

Example:
Setting: 
Default: 100%
Audience: GroupA = 100, GroupB = 0

Evaluate:
new TargetingContext
{ Groups = new List<string>() { "GroupB " } }

The return will be true because GroupB always evaluate as false, hence the default percentage applied.

**Comment by jimmyca15** [comment]
That's the expected behavior.

**Comment by yuanyi2121** [comment]
Hmm, if I have 100 groups and only want to turn a feature off for one group, how am I supposed to do that? I think the expected behavior should be if I want a group to be 0%, they should be 0%.

**Comment by jimmyca15** [comment]
The 100 groups would need to be specified with rollout percentages of 100 with the singular disabled group being omitted.

**Comment by yuanyi2121** [comment]
Yes, that's the point - right now I have to explicitly define 99 groups with 100% and one with 0% (or set 0% as default). And this is the better case where I can figure what the other 99 groups are. What if I want to disable a feature for a certain IP address?

The correct behavior should be, IMHO - if there are any group matches, the code should never fall back to the default settings, it should instead aggregate the result of all the matched groups.

**Comment by jimmyca15** [comment]
@yuanyi2121 thanks for the feedback. We can consider adding an option to the targeting parameters to allow a behavior like that.

**Comment by jimmyca15** [comment]
Resolved with the addition of exclusion in #218. The new exclusion feature is available in the latest stable release (2.6.1)
