### ISSUE TITLE
Add capability to let users define how percentage values should be calculated

### ISSUE THREAD

**Issue by pardahlman** [microsoft/FeatureManagement-Dotnet#124]
In a distributed system scenario, features may span over multiple applications an either be enabled or disabled for the entire execution (think trace) in a global sense. That is, a feature that is evaluated to be enabled in system A should be enabled in downstream systems for the entire execution. This is not a problem with `Microsoft.TimeWindow`, as it is either on or off. However, it does not work for filters with percentage-based roll outs.

The filters  `Microsoft.Percentage` and `Microsoft.Targeting` works in similar ways:

1. Identify which percentage value that should be used for the current evaluation (either `Value` or a `RolloutPercentage`/`DefaultRolloutPercentage`)
2. Generate a random percentage value 
3. Compare the random value with the value calculated in step 1

I think it would be great if step 2. is performed in a service with a public interface that can be replaced by the user. That way, the "random percentage value" can be extracted from query-parameters, headers or any other way that the value from system A has been propagated to downstream systems.

**Comment by jimmyca15** [comment]
I think exposing the capability to calculate the percentage is reasonable. However, one thing I want to mention is that Microsoft.Percentage and Microsoft.Targeting differ. Microsoft.Percentage always uses a random percentage. Microsoft.Targeting produces a stable percentage using input data (user, groups, feature name). As long as every part of the system has the same values for these it should produce the same result. From your ask though it sounds like you are trying to avoid the calculation altogether though, is that right?
