### ISSUE TITLE
Adding typed structures for on/off feature flags

### ISSUE THREAD

**Issue by OsirisTerje** [microsoft/FeatureManagement-Dotnet#125]
Is it possible to add usage of typed structures instead of the string-based one have now?
Eg. defining the features as
```cs
public class Features
{
    public bool FeatureA {get; set; }
    public bool FeatureB {get; set; }
    public bool FeatureC {get; set; }
}
```
Then one could extract out this class from the FeatureManager, even skip the IsEnabled, and just use the bools directly.

(This is the way the [FeatureToggle](https://github.com/jason-roberts/FeatureToggle) library works, which is very nice. 

Having to use strings, even if added as const strings in a class is kind of odd and opens up for using strings inside the production code itself.  Nothing prevents using a literal string as a parameter to the IsEnabled method. 

This is also the way one normally extract configuration data from IConfiguration, so it should be easy to just build on top of that.

**Comment by jimmyca15** [comment]
This is a bit of syntax sugar and we might be able to provide an extension method for it. 

> Having to use strings, even if added as const strings in a class is kind of odd

I'm not sure where this stance comes from. The features are declared in some system and the string in this case would be a constant reference to the feature. It's difficult to avoid. There are cons to having property names being used in binding. For example, code refactoring can result in complications when binding takes place. This is why attribute based deserialization exists that takes string as an attribute parameter. It separates data binding from the type definition, which is usually a beneficial pattern.

**Comment by jimmyca15** [comment]
Current recommendation is to use string mapping for feature flags and avoid type definition data binding.
