### ISSUE TITLE
Other di containers

### ISSUE THREAD

**Issue by da1rren** [microsoft/FeatureManagement-Dotnet#126]
Hey Guys,

We're attempting to use this in a .net framework application that uses autofac.  While attempting to register the various dependencies:

* ConfigurationFeatureDefinitionProvider
* FeatureManager
* EmptySessionManager
* FeatureManagerSnapshot

 I've discovered that they are all sealed, is there any guidance or is it even possible to use this without resorting to reflection hacks?

**Comment by jeffcollaboro** [comment]
... or any other number of containers, Simple Injector etc, These classes are the public interface into feature flags they shouldn't be internal, we need to instantiate them to use this.

**Comment by danielmackay** [comment]
We're having this problem also.  It would be great to see some guidance of how to use the `FeatureManager` with other IoC containers.

**Comment by zhiyuanliang-ms** [comment]
Update:
The PR #302 of exposing FeatureManager to public has been merged into main branch. Now the FeatureManagement should be compatible with other DI framework.

**Comment by zhiyuanliang-ms** [comment]
Fixed in release 3.1.0

**Comment by zhiyuanliang-ms** [comment]
Fixed in release 3.1.0

**Comment by zhiyuanliang-ms** [comment]
I created a repo to demonstrate how to use Microsoft.FeatureManagement in third-party Di containers: https://github.com/zhiyuanliang-ms/FeatureManagement-Dotnet-DependencyInjection
:)
