### ISSUE TITLE
FeatureRequest: Exclusion ability for Feature Management

### ISSUE THREAD

**Issue by amharris1331** [microsoft/FeatureManagement-Dotnet#128]
It would be great if there was a way to blackList a user/group in a Feature Filter.  I know that technically I could create another flight containing all of the users/groups that I would wish to blackList for a feature, but it would be really beneficial to be able to have both whiteLists and blackLists in the same place.

**Comment by amharris1331** [comment]
Has there been any progress with this request?

**Comment by leonids2005** [comment]
Sorry, for saying this ( I am not the person who does maintain this tool) but you can easily implement your own FeatureFilter which does what you want.

Take the existing code as an example and extend it. This is what we have done :).   
But this is just my private opinion.

**Comment by amharris1331** [comment]
Thanks for the feedback and taking the time to reply back!  I will pass your advice on to the engineer requesting this feature.

Thanks again!

Best,

Amanda Harris

**Comment by jimmyca15** [comment]
Tracking in https://github.com/microsoft/FeatureManagement-Dotnet/issues/123
