### ISSUE TITLE
Deploying a Feature Flag with Custom Filters but Disabled using az cli

### ISSUE THREAD

**Issue by nexaddo** [microsoft/FeatureManagement-Dotnet#130]
When deploying a feature flag with custom filters and the enabled property set to false using `az appconfig kv import` results in the custom filters being dropped when viewing the feature flag json using 'Advanced Edit' in the Feature Manager section of the App Configuration resource in the azure portal.

With no enabled property set using custom filters:

Feature Management Section of appsettings.json:

```
{
  "FeatureManagement": {
    "AccountInformation": {
      "EnabledFor": [{
        "Name": "RequiredConditions",
        "Parameters": {
          "RequiredClaims": [{
            "accountpackageid": "Premier"
          }],
          "RequiredRoles": [
            "AccountOwner"
          ],
          "RequiredPartnerIds": [{
            "sapphire_partner": "15000"
          }]
        }
      }]
    }
  }
}
```

Json from Advanced Edit:
```
{
  "id": "AccountInformation",
  "description": null,
  "enabled": true,
  "conditions": {
    "client_filters": [{
      "name": "RequiredConditions",
      "parameters": {
        "RequiredClaims": [{
          "accountpackageid": "Gold"
        }],
        "RequiredRoles": [
          "AccountOwner"
        ],
        "RequiredPartnerIds": [{
          "partner_id": "1000"
        }]
      }
    }]
  }
}
```

With enabled property set to `false`:

```
{
  "FeatureManagement": {
    "AccountInformation": {
      "Enabled": false,
      "EnabledFor": [{
        "Name": "RequiredConditions",
        "Parameters": {
          "RequiredClaims": [{
            "accountpackageid": "Gold"
          }],
          "RequiredRoles": [
            "AccountOwner"
          ],
          "RequiredPartnerIds": [{
            "partner_id": "1000"
          }]
        }
      }]
    }
  }
}
```

Viewing with Advanced Edit:

```
{
  "id": "AccountInformation",
  "description": null,
  "enabled": false,
  "conditions": {
    "client_filters": []
  }
}
```

Is there something I'm missing on the ASP Net Core side of things with the appsettings properties for setting custom filters and having the feature flag be set to a disabled state by default when deployed to the Azure App Configuration resource?

Is this intended behavior? Is there a workaround?

**Comment by avanigupta** [comment]
Hello @nexaddo, if you want to import a feature flag which is disabled but also has custom filters, you can do this in two steps:
1. Use `az appconfig kv import` command to import your feature flag to App Config with all filters.
2. Use `az appconfig feature disable` command to disable the feature flag without losing its filters.

Hope that helps!

**Comment by nexaddo** [comment]
> Hello @nexaddo, if you want to import a feature flag which is disabled but also has custom filters, you can do this in two steps:
> 
> 1. Use `az appconfig kv import` command to import your feature flag to App Config with all filters. Now your AppConfig store has a feature flag that is enabled and has all your custom filters.
> 2. Use `az appconfig feature disable` command to disable the feature flag without losing its filters.
> 
> Hope that helps!

Thank you! I'll give that a try and see if that gets us where we want to be.

**Comment by jimmyca15** [comment]
Issue hasn't had any updates. Please feel free to ping if there's still any concerns.
