### ISSUE TITLE
services.AddApplicationInsightsKubernetesEnricher()

### ISSUE THREAD

**Issue by mattsage1991** [microsoft/FeatureManagement-Dotnet#135]
When adding services.AddApplicationInsightsKubernetesEnricher() into ConfigureServices, IFeatureManager doesn't return the latest state of the feature from AAC, it works when I remove it. 

Is this something you will resolve in the near future? Thought I'd raise it as it took me a while to find out why it wasn't working, in case it helps anyone else.

**Comment by mattsage1991** [comment]
I guess this is more of a problem with AAC than FeatureManagement?

**Comment by jimmyca15** [comment]
If `AddApplicationInsightsKubernetesEnricher` is causing the issue, it may be some unexpected pattern being used by that call. IFeatureManager relies on typical configuration reload notifications to ensure that the latest state of features is available. It may be that `AddApplicationInsightsKubernetesEnricher` is somehow breaking that notification chain.

**Comment by jimmyca15** [comment]
Tracked here (https://github.com/microsoft/ApplicationInsights-Kubernetes/issues/236) in the repo that exposes the `AddApplicationInsightsKubernetesEnricher` API and it looks like they have a PR out to address the issue.
