### ISSUE TITLE
Filter and group features by prefix in the Azure Portal

### ISSUE THREAD

**Issue by mack0196** [microsoft/FeatureManagement-Dotnet#153]
Like Azure App Configuration Configuration Manager, have a filter on the portal to filter for prefixes; application ID prefixes are the documentation guidance for configuration and feature multitenancy.

In addition, it would be really nice to group by feature and configuration name prefix.

**Comment by zhiyuanliang-ms** [comment]
Hi, @mack0196 
If my understanding is correct, the Portal has supported the scenario you've mentioned.
![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/141655842/3cb8d1ba-ff9c-4cd4-b37c-b9013242bca4)
![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/141655842/8758a32f-c18d-4df9-b15f-c1eef7d6c1c2)
Could you double check about this?
