### ISSUE TITLE
Wildcard before the filter

### ISSUE THREAD

**Issue by mack0196** [microsoft/FeatureManagement-Dotnet#154]
I can filter configuration manager using "ABCD*" but I cannot put the start in the middle or begging of the search string like "*XYZ" or "AB*YZ".

![image](https://user-images.githubusercontent.com/6463105/141857143-3423123b-4798-41b7-aff1-bb177278045c.png)

**Comment by jimmyca15** [comment]
This is a feature request for Azure App Configuration. It's being tracked here https://github.com/Azure/AppConfiguration/issues/342
