### ISSUE TITLE
Feature filtering first by FilterKey, and then Label, seems not working

### ISSUE THREAD

**Issue by luismanez** [microsoft/FeatureManagement-Dotnet#158]
Hi,
I´m having an issue when filtering Features using the library (maybe I´m missing something).

I have a multi-tenant app, so following [MS best practices](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-best-practices#key-groupings), I want to use Key prefixes and Labels to organize Features. My idea is to use the prefixed Key to segment by customer, and then, use the Label to segment by Environment (some customers will have the same Feature in different envs). Here´s an example of this:

![image](https://user-images.githubusercontent.com/9392197/147242157-7c6c56a8-9fd6-4dd3-ab63-6a2d2eac3fd0.png)

We have the Feature __BestDeals__ for 2 customers (Contoso / Marvel), but also, the Contoso customer has the Default label (env), and also another one for UAT env. Marvel only have the BestDeals Feature with the Default (null) Label, as they don´t have different Environments for my App. Also, the __BlackFriday__ feature only exists for Contoso, with no specific value per environment.

What would be the proper __Select__ calls inside __UseFeatureFlags__ to load, first, all the Features that the Key value contains the specific Customer, and then, overwrite the values if there´s a specific environment??. For example, I want Contoso´s features, for UAT enviroment (if a Feature has no UAT Label (env), then the Default (null Label) value is taken.

I´ve tried different __Select__ combinations with no luck. As far as I understand, it should be:

```csharp
                        var settings = config.Build();
                        config.AddAzureAppConfiguration(options =>
                            options
                            .Connect(settings["ConnectionStrings:AzureAppConfiguration"])
                            .UseFeatureFlags(featureFlagOptions => {
                                featureFlagOptions.Select("contoso/*", LabelFilter.Null);
                                featureFlagOptions.Select(KeyFilter.Any, "UAT");
                            })
                            );
```

However, with that setup, when I run the following code:

```csharp
            var featureNames = new List<string>();

            await foreach (string featureName in _featureManager.GetFeatureNamesAsync().ConfigureAwait(false))
            {
                var enabled = await IsEnabled(featureName);
                featureNames.Add($"{featureName}=>{enabled}");
            }

            return featureNames;
```

it returns:

```json
[
    "BestDeals=>False",
    "BlackFriday=>True"
]
```
However, the __BestDeals__ feature, for Contoso, and UAT env, is enabled...

In __Fiddler__ tool, I see the following calls to the AppConfig REST Api...

```
# returns all the settings in the AppConfig service with no filter (feature flags, and other settings)
GET /kv/?key=%2A&label=%00&api-version=1.0 HTTP/1.1

# returns Feature flags with UAT Label
GET /kv/?key=.appconfig.featureflag%2F%2A&label=UAT&api-version=1.0 HTTP/1.1

# previous 2 calls are the ones done by the Select calls in UseFeatureFlags, before calling the code that iterates all Feature names and check if the feature is enabled.

# now the code that itereates all the features calling IsEnabled does these calls:

GET /kv/?key=.appconfig.featureflag%2Fcontoso%2F%2A&label=%00&$select=key%2C%20etag&api-version=1.0 HTTP/1.1
# previous call does the proper filter by key (Contoso) but with No Label

GET /kv/?key=.appconfig.featureflag%2Fcontoso%2F%2A&label=%00&api-version=1.0 HTTP/1.1
# same as previous call, but getting all the fields

GET /kv/?key=.appconfig.featureflag%2F%2A&label=UAT&$select=key%2C%20etag&api-version=1.0 HTTP/1.1
# filtering by Label, but not the Key prefix

GET /kv/?key=.appconfig.featureflag%2F%2A&label=UAT&api-version=1.0 HTTP/1.1
# getting only Feature flags for UAT label
```

I´d say all the required data is in the "Aggregate" of all these request. However, when asking if the "BestDeals" feature is enabled, it says False, when it should say True.

Am I doing something wrong?

BTW, if I use the Label to segment by customer, and then the prefix to segment by environment, the following setup works fine:

```chsarp
featureFlagOptions.Select(KeyFilter.Any, "Contoso");
featureFlagOptions.Select("UAT/*");
```

Any idea?

Many thanks.

**Comment by luismanez** [comment]
Any thoughts here @jimmyca15 ??
Thanks.

**Comment by jimmyca15** [comment]
Before digging in to deep, I noticed that you will have to add a flag for each customer with this approach. Did you consider using the [targeting feature filter](https://github.com/microsoft/FeatureManagement-Dotnet#microsofttargeting) to support enabling features for certain customers? This will result in less feature flags being defined and then the solution will change entirely.

**Comment by luismanez** [comment]
Thanks for your reply @jimmyca15 ... hmmm.. that might work, but would require some custom code to set the _TargetingContext_ to use the Tenant (customer) as _Groups_.

Anyway, my scenario should work. If we take the Best practices article (https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-best-practices#key-groupings), it states:


> Key prefixes are the beginning parts of keys. You can logically group a set of keys by using the same prefix in their names. Prefixes can contain multiple components connected by a delimiter, such as /, similar to a URL path, to form a namespace. Such hierarchies are useful when you're storing keys for many applications and microservices in one App Configuration store.

So you can easily image multiple microservices, and using the Key, so that each service reads only their values (and then, if you want, you use the Label to segment per environment).

Can I test anything else, or do, to help here? BTW, would be great if the package includes SourceLink info, so we can Debug the code easily :)

Thanks again!

**Comment by jimmyca15** [comment]
If you only select the UAT feature like below does it get enabled?

```
                        var settings = config.Build();
                        config.AddAzureAppConfiguration(options =>
                            options
                            .Connect(settings["ConnectionStrings:AzureAppConfiguration"])
                            .UseFeatureFlags(featureFlagOptions => {
                                featureFlagOptions.Select(KeyFilter.Any, "UAT");
                            })
                            );
```

**Comment by luismanez** [comment]
Could you take a look to this repo that reproduces my issue?
https://github.com/luismanez/FeatureManagement-Dotnet-issue158

Please, create the feature flags as per the image in my first comment, and you should see the issue (I´m using .net core 3.1 with latest packages in AppConfig and FeatureManagement)

I´ve tested your code, but still gets Disabled, and also, if I create another different Feature for another customer (_.appconfig.featureflag/gotham/SentimentAnalysis_), with __UAT__ label, that feature is also returned when calling __GetFeatureNamesAsync()__ which is not right either, cos I´m only interested in Features for Contoso.

Just to discard things, all my tests are starting the web app from scratch, and without updating any Feature. I mean, cache is not playing here.

Many thanks again.

**Comment by jimmyca15** [comment]
@luizmanez

One thing I'd like to mention is that Azure App Configuration pulls all settings with no label by default. This includes feature flags. So if you have feature flags with no label, they will get pulled down. With your setup this is problematic because I see you have two features with the same name with no label (BestDeals). If you were to check if the "BestDeals" feature is enabled in your app, there would be no way to differentiate between the two different feature flags you have stored in Azure App Configuration (contoso vs marvel). If not aware of this, it could cause unexpected behavior.

If you want to avoid pulling all key-values then you need to modify your configuration select statement like:

```
                        var settings = config.Build();
                        config.AddAzureAppConfiguration(options =>
                            options
                            .Connect(settings["ConnectionStrings:AzureAppConfiguration"])
                            .Select("_", LabelFilter.Null) // Select non existent '_' key to discard configuration.
                            .UseFeatureFlags(featureFlagOptions => {
                                featureFlagOptions.Select(KeyFilter.Any, "UAT"); // Only pulls feature flags with "UAT" label.
                            })
                            );
```

**Comment by luismanez** [comment]
> If you were to check if the "BestDeals" feature is enabled in your app, there would be no way to differentiate between the two different feature flags you have stored in Azure App Configuration (contoso vs marvel).

I understand what you´re saying, but I thought this wouldn´t happen, as I´m "selecting" the features with key containing "contoso/*"

```
featureFlagOptions.Select("contoso/*", LabelFilter.Null);
```

My believe was that it gets all settings, then, it "selects" the ones having the Key _contoso_, and then, if there are Labels for that settings, it overwrites the value with the proper one for the label (UAT). Is not how it works? 

So, is there any way to do the following:
  1. Select all the settings
  2. Now, for settings with same name (i.e: BestDeals), get the ones with Key containing the passed value (contoso) and discard the settings that don´t contain contoso
  3. Now, if any of these settings, have the Label UAT, use that value, otherwise, get the value of the default Label

Thanks!

**Comment by jimmyca15** [comment]
No you can only register one. In your scenario you could define a new interface that your implementation of ITargetingContextAccessor relies on. Then you could provide the two implementations you mentioned through that interface..

**Comment by luismanez** [comment]
I see. OK, closing the issue. Many thanks for your help and patience, really appreciate it.

Cheers.
