### ISSUE TITLE
Demo app failed with internal server error

### ISSUE THREAD

**Issue by harrchen88** [microsoft/FeatureManagement-Dotnet#16]
I am trying to run the demo locally but with App Configure service using regular endpoint connection string instead of managed identity.  Got an error below (screenshot attached):
An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'Boolean Roslyn.Utilities.IObjectWritable.get_ShouldReuseInSerialization()'.
Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(string assemblyName, CSharpCompilationOptions options, IEnumerable<SyntaxTree> syntaxTrees, 
IEnumerable<MetadataReference> references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, bool isSubmission)

Stack trace:
MissingMethodException: Method not found: 'Boolean Roslyn.Utilities.IObjectWritable.get_ShouldReuseInSerialization()'.
Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(string assemblyName, CSharpCompilationOptions options, IEnumerable<SyntaxTree> syntaxTrees, IEnumerable<MetadataReference> references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, bool isSubmission)
Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(string relativePath)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(string normalizedPath)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageLoader.Load(PageActionDescriptor actionDescriptor)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler+<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.Azure.AppConfiguration.AspNetCore.AzureAppConfigurationRefreshMiddleware+<InvokeAsync>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
![appconfigsettings](https://user-images.githubusercontent.com/39616938/65844726-fba28180-e354-11e9-9c33-47514b16e17c.JPG)
![appconfigError](https://user-images.githubusercontent.com/39616938/65844728-fba28180-e354-11e9-886f-4373c3b72e7f.JPG)

**Comment by zhenlan** [comment]
Moved to https://github.com/Azure/AppConfiguration/issues/175.

@harrchen88 please use https://github.com/Azure/AppConfiguration repo for issues related to App Configuration in the future. This repo is specifically for `Microsoft.FeatureManagement.*` libraries.
