### ISSUE TITLE
Need to have capability to add multiple feature definition providers

### ISSUE THREAD

**Issue by adityamagadi** [microsoft/FeatureManagement-Dotnet#172]
I am using this library for enabling feature flagging in a multi tenant based environment, that would require me to provide multiple feature definitions. However i see that the library at this moment does not support this, it would be great if we can provide multiple sources and specify the source to be used at runtime depending on the tenant.

**Comment by jimmyca15** [comment]
Have you considered implementing a custom feature definition provider yourself that does delegation as necessary to the different providers you are referring to?

**Comment by jimmyca15** [comment]
This is supported by implementing an IFeatureDefinitionProvider that delegates to multiple sources.
