### ISSUE TITLE
featurebits.core

### ISSUE THREAD

**Issue by amafernandes** [microsoft/FeatureManagement-Dotnet#18]
There is any relation with the development of the package featurebits.core, [nuget](https://www.nuget.org/packages/FeatureBits.Core), [github](https://github.com/microsoft/featurebits).
Both packages seems to have related goals, they work both on netcore.
It would be better, IMHO, to have a unified approach to feature flags.

**Comment by themitchk** [comment]
Correlating issue from FeatureBits repo:
https://github.com/microsoft/featurebits/issues/55

**Comment by zhenlan** [comment]
Correlating issue from App Configuration repo:
https://github.com/Azure/AppConfiguration/issues/112
