### ISSUE TITLE
Can Microsoft.TimeWindow filter support recurring time?

### ISSUE THREAD

**Issue by sacrajit** [microsoft/FeatureManagement-Dotnet#194]
Where as enabling a feature during a certain duration once, can be useful for promotional capabilities, I found scenarios where one may need to turn on a feature during a low or high traffic period of a day or certain days of a week. Having the ability to combine days of week(or All) along with start and end time will be very helpful.

Thanks!

**Comment by jimmyca15** [comment]
@sacrajit

It does not support a recurring time, but if that is something that makes sense we can look into adding a built-in filter to do it. Alternatively, you can implement an `IFeatureFilter` to create a recurring feature flag in your application.

Here's an [example ](https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/BrowserFilter.cs) of a custom feature filter implementation.

**Comment by zhiyuanliang-ms** [comment]
Hi, @sacrajit 
We are working on this. Please see the PR: https://github.com/microsoft/FeatureManagement-Dotnet/pull/256.

**Comment by zhiyuanliang-ms** [comment]
@sacrajit #266 merged

In our next stable release 3.3.0, the recurring time window filter will be available.

**Comment by zhiyuanliang-ms** [comment]
@sacrajit 

`Microsoft.FeatureManagement` v3.3.0 has been released.
