### ISSUE TITLE
Feature Flags and Deployment Slots

### ISSUE THREAD

**Issue by jcr010910** [microsoft/FeatureManagement-Dotnet#197]
let's assume we started working on new feature 4 sprints ago and the feature flag is "OFF" for production.
Now, we want to enable **specific** users to opt-in the new UX deployed to staging environment.

so mainly I want to combine both of [TargetingFilter](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-targetingfilter-aspnet-core) and [Route production traffic manually](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#route-production-traffic-manually) together.
How can we achieve that?

@jimmyca15

**Comment by jimmyca15** [comment]
If I'm understanding this correctly the desire is to have the requests from a certain user route to the staging slot if they are targeted for some feature. 

The optimal way for this to happen is if the App Service routing engine could be aware of the targeting rules established, but that integration does not exist. Thus, the problem will have to be solved in your app level.

You can implement a middleware that checks if a user is targeted for the staging slot feature, and if they are then you can return a redirect response.
