### ISSUE TITLE
Enable data to be passed to feature filters in console apps and frameworks that do not have a context.

### ISSUE THREAD

**Issue by jimmyca15** [microsoft/FeatureManagement-Dotnet#2]
At the moment console apps do not have a way to pass data to the feature management system to evaluate feature state based on contextual data. As an example, imagine I am processing notifications in a console app from a file. Part of the processing might trigger some additional functionality based off of criteria within the notification. We could assume that data is notificationId. We need to be able to propagate this data to feature filters to check if a feature is enabled.

This is available to frameworks like ASP.NET and ASP.NET Core by utilizing the HTTP Context which flows ambiently through the application. During the request, assorted items can be added to the context and accessed in feature filters.

To keep design and usage consistent across all types of applications I believe the best approach here would be to add a way to flow contextual data into the feature management pipeline to be utilized during evaluation.

**Comment by jimmyca15** [comment]
This has been enabled with PR #14

**Comment by jimmyca15** [comment]
Release tag: https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.0.0-preview-010610001-1263

**Comment by AAATechGuy** [comment]
thank you
