### ISSUE TITLE
Feature Request: Add "Not" to RequirementType to disable endpoint using FeatureGateAttribute when flag set to true

### ISSUE THREAD

**Issue by michaelrp** [microsoft/FeatureManagement-Dotnet#202]
Using the `FeatureGateAttribute` we can only disable an endpoint attribute when a flag is set to false. It would be useful to be able to disable an endpoint when a flag is set to true.

This would allow using one feature flag to turn on _and_ off a set of features. Something like:

``` Javascript
{
  "FeatureManagement": {
    "FeatureA": true
  }
}
```

``` C#
[FeatureGate(FeatureFlags.FeatureA)]
public async Task ThisWillWorkAsync()
```
``` C#
[FeatureGate(RequirementType.Not(FeatureFlags.FeatureA))]
public async Task ThisWillNotWorkAsync()
```

**Comment by brental** [comment]
Rather than adding a single Not requirement type, it would probably be better to add a NotAny and a NotAll requirement type. This would allow for the inverse / negation of both the two current requirement types rather than just the Any OR All requirement type. It would also be clearer what the new requirement types do.

These two options would also mean that the current negate option of the FeatureTagHelper could be made obsolete in favour of negate functionality that works for the entire library.

**Comment by trconnolley** [comment]
Agreed, it would be a very helpful feature

**Comment by darkalfx** [comment]
We need this 100%, would be nice if they started including basic features with their apis....

**Comment by jimmyca15** [comment]
This scenario makes sense. I think we should support this with a Negate property on FeatureGateAttribute.

@rossgrambo @zhiyuanliang-ms

**Comment by zhiyuanliang-ms** [comment]
@michaelrp @brental @darkalfx @trconnolley Hey, guys! Sorry for late response. I think we will land on add a `Negate` property to `FeatureGateAttribute` which is similar to the implementation of [`FeatureTagHelper`](https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/src/Microsoft.FeatureManagement.AspNetCore/TagHelpers/FeatureTagHelper.cs#L33)

Currently, we support the following usage of `FeatureGateAttribute`:

``` C#
[FeatureGate("Home")]
```
and
``` C#
[FeatureGate(requirement: RequirementType.Any, ["Alpha", "Beta"])]
```

After adding `Netage` property, we will add another constructor for `FeatureGateAttribute`, which will allow the following usage:
``` C#
[FeatureGate(requirement: RequirementType.Any, negate: true, ["Alpha", "Beta"])]
```

**Comment by michaelrp** [comment]
Sounds good!

**Comment by zhiyuanliang-ms** [comment]
#519 merged.

**Comment by michaelrp** [comment]
Awesome, thank you!

**Comment by OskarKlintrot** [comment]
@zhiyuanliang-ms Any news when this will be released so we can use it?

**Comment by zhiyuanliang-ms** [comment]
Hi, @OskarKlintrot It seems like this feature missed the train of 4.0.0 release. Sorry for that.

We are going to release 4.1.0 this week. This feature will be included. Thank you for the patience!
