### ISSUE TITLE
Synchronous Evaluation

### ISSUE THREAD

**Issue by everettcomstock** [microsoft/FeatureManagement-Dotnet#208]
I'm curious as to the reasoning for why support synchronous evaluation was removed from the library? It seems like internally many operations evaluate synchronously, and are then wrapped into tasks as to fit into async processing paradigm.

For instance:
https://github.com/microsoft/FeatureManagement-Dotnet/blob/9931f07eda453fe099e1bf39dc36315d26c5a985/src/Microsoft.FeatureManagement/ConfigurationFeatureFlagDefinitionProvider.cs#L60

I recognize that asynchronous operations can be processed synchronously... but it seems like offering both processing paradigms would allow developers to more accurately convey intent, and in turn lead to cleaner code.

**Comment by jimmyca15** [comment]
Hello @everettcomstock, the decision ultimately came down to the complexity of the library. We felt that the benefits of exposing interfaces, types, and examples for both synchronous and asynchronous programming models did not match the added complexity.
