### ISSUE TITLE
How stable are dynamic features?

### ISSUE THREAD

**Issue by vguzmanp** [microsoft/FeatureManagement-Dotnet#217]
We are looking into using the [3.0.0-preview](https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/3.0.0-preview) version of the library, mainly because of the "dynamic features" feature.

As we see it has been rolled back from main, we are wondering how stable it is. 
Can we use it for a production environment? Are there any major changes to be expected?

**Comment by jimmyca15** [comment]
@vguzmanp 

We previewed dynamic features but ultimately feel like they need some more thought and changes on our end. For the time being we won't be promoting 3.0.0-preview/dynamic features to a stable release. When they are re-introduced, I do expect that there will be changes. How major, I'm not sure at the moment.

In the meantime we will be working on releasing some built-up enhancements for feature flags in our 2.x train. 

Let me know if this helps.

**Comment by vguzmanp** [comment]
Clear, thanks!
We will work around it until it is stable.
