### ISSUE TITLE
Can I use Microsoft Feature Management – Feature Flags in other than .NET Core Frameworks ?

### ISSUE THREAD

**Issue by milyas-salik** [microsoft/FeatureManagement-Dotnet#220]
Hi,

Can I use this library (Microsoft.FeatureManagement) for other than .Net Core Applications such as ASP.NET MVC , ASP.NET Web APPLICATION, Console Application, Windows Application built on .NET.

If Yes can you provide some examples/steps to carry on or link to refer.

I have Solution built on .NET which as web applications, web apis and windows application built on .NET.
@avanigupta, @amerjusupovic, @jimmyca15, @jason-roberts 

Thanks.

**Comment by rossgrambo** [comment]
Hello @milyas-salik!

Yes, you should be able to use this library for those applications. Our [examples folder ](https://github.com/microsoft/FeatureManagement-Dotnet/tree/main/examples) should be able to help.

We explicitly add support for ASP.NET via the `Microsoft.FeatureManagement.AspNetCore` package, here's the quickstart for it: https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core?tabs=core6x 

In our examples folder, there's an example for a console application, which I believe applies to Windows Applications as well https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/ConsoleApp/Program.cs

Hope this helps!
