### ISSUE TITLE
Local configuration and remote configuration

### ISSUE THREAD

**Issue by sathishkumarkaliavaradhan-okta** [microsoft/FeatureManagement-Dotnet#230]
Hi @jimmyca15 ,

I am trying to enable the local feature flag configuration for QA testing and remote configuration for production. Based on the documentation my understanding is that when I addjson file with the "FeatureManagement" section defined SDK loads the value from the appsettings.json file even though I have added the AzureAppConfiguration option.

     ```       var configuration = new ConfigurationBuilder()
                .AddJsonFile(LocalFeatureFlagConfigurationFile)
                .AddAzureAppConfiguration(options =>
                {
                    // To connect with feature flag CDN edge.
                    options.Connect(this.featureProviderConfiguration.RemoteConfigurationConnectionString);
                    options.UseFeatureFlags(configure
                        => configure.CacheExpirationInterval
                        = TimeSpan.FromMinutes(this.featureProviderConfiguration.RemoteConfigurationCacheExpiration));
                    configurationRefresher = options.GetRefresher();
                })
                .Build();     ```

The above configuration works the other way around where always try to load the configuration from Azure. 

I would like to add an optional appsettings.json file locally for QA testing with feature flags defined then SDK should check the Azure and when the appsettings.json file doesn't contain the "FeatureManagement" section then it should load from Azure. could you please let me know how do I support this scenario?

Thanks,
Sathishkumar

**Comment by rossgrambo** [comment]
Hello @sathishkumarkaliavaradhan-okta ,

I joined the App Configuration team a couple months ago, but I can offer a suggestion here.

The recommended way to achieve that separation is to ensure that the QA configuration isn't loaded at all for production (and vise versa). You could explicitly do a check for QA/Production and adjust the configuration as needed. There should be an `IsDevelopment()` method offered somewhere in your startup that reads the `DOTNET_ENVIRONMENT` or `ASPNETCORE_ENVIRONMENT` environment variable. It depends what your startup files look like- but here's a webhost example:

```
public static IWebHost BuildWebHost(string[] args)
{
    return WebHost.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((hostingContext, configuration) =>
        {
            if (hostingContext.HostingEnvironment.IsDevelopment())
            {
                configuration.AddJsonFile(LocalFeatureFlagConfigurationFile);
            }
            else
            {
                configuration.AddAzureAppConfiguration(options =>
                {
                    // To connect with feature flag CDN edge.
                    options.Connect(this.featureProviderConfiguration.RemoteConfigurationConnectionString);
                    options.UseFeatureFlags(configure
                        => configure.CacheExpirationInterval
                        = TimeSpan.FromMinutes(this.featureProviderConfiguration.RemoteConfigurationCacheExpiration));
                    configurationRefresher = options.GetRefresher();
                });
            }
        })
        .UseStartup<Startup>()
        .Build();
}
```

Let me know if this approach doesn't work for you.

Links:
* Environments & isDevelopment: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1 
* FeatureManagement example that uses isDevelopment (not in the same way, but could be useful): https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/Startup.cs#L73
