### ISSUE TITLE
Support of Targeting(percentage) and custom filter

### ISSUE THREAD

**Issue by sathishkumarkaliavaradhan-okta** [microsoft/FeatureManagement-Dotnet#232]
Hi @rossgrambo, @jimmyca15 ,

Good Morning.

I have two more questions and wanted to follow up with you.

1) In the Azure portal, the feature flag filter allows choosing only "Targeting", "Time window" and "Custom" options. I have attached a screenshot of it

![image003](https://github.com/microsoft/FeatureManagement-Dotnet/assets/122304514/a626b843-09af-4be5-9fac-228e617906a7)

We would like to allow both Targeting (percentage) and Custom filters. Basically, we would like to turn on features only for the percentage of custom-filtered customers. For example, turn on the feature for 30% of the particular app version of the customer.

2) Is it possible to add multiple custom filters? or can add one custom filter with different parameters?

Thanks,
Sathishkumar

**Comment by rossgrambo** [comment]
Hello @sathishkumarkaliavaradhan-okta,

The "Custom" option here handles multiple filters. Each of those filters could be either be custom or a standard filter.

For example, here's a screenshot of one of my "Custom" filters that uses two standard filters:
<img width="388" alt="image" src="https://github.com/microsoft/FeatureManagement-Dotnet/assets/10674897/e20f0a9f-5bf1-4dff-8d4f-b30def12683f">

I find it easier to use the "Advanced Edit" instead of "Edit" on the list of features. Within there, you can see `"client_filters": [` is an array that accepts multiple filters. Whether they're custom or not. 

You might want to create a targeting filter via "Edit" first, and then use "Advanced Edit" to add your custom filter afterwards. Once you do, the portal will understand it's now a multiple-filter "Custom" filter and show it appropriately in the "Edit" screen.

Hope this makes sense! Let me know if you have any issues.

**Comment by sathishkumarkaliavaradhan-okta** [comment]
Thank you so much @rossgrambo,

It's really helpful, I saw the same in the UI but kind of confusing because it shows at a time only one of the filters can be selected but the time filter appears in the custom section. 

I have follow-up questions 
1) if the target filter with a 50% percentage of the customer and another custom filter checks only the customer who is using version >=1.0.0.0 this case how does the evaluation happen? are they AND the operation of all the filters?

2) Let's say I have a custom filter "EmployeeFilter" with multiple parameters like "EmployeeName": "Test" and "Department": "HR" In my evaluation I will read these two parameters and decide the result. Can I have multiple parameters for the single custom filter?

Thanks,
Sathishkumar

**Comment by rossgrambo** [comment]
Hello @sathishkumarkaliavaradhan-okta,

1. The filters use "Any" logic. So the first one is evaluated, if it returns true, we stop immediately and return enabled. If it's not true, we go to the next filter. So in this case, you could not do what you're proposing, unless you split it into multiple features, each with 1 filter, and do the AND logic yourself. Or write your own custom filter that does both checks.
    * We have a preview release that adds "All" logic in a field called `RequirementType`- https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.6.0-preview. If you're open to using preview, you can utilize it.
      * Note: If you use this preview, you'll have to add the `RequirementType` field in the portal via Advanced Edit, because the portal doesn't know about the field yet. Those changes are on the way. 
2. Yep! You can, you just have to define those fields yourself. You'd define them similarly to our BrowserFilter example, just adding multiple fields to [`BrowserFilterSettings`]( https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/BrowserFilterSettings.cs). And then using whatever logic you want in your custom filter- [`BrowserFilter`](https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/BrowserFilter.cs).
In the portal, I believe your filter would look something like:
```
{
  "name": "MyEmployeeFilter",
  "parameters": {
    "EmployeeName": "Test"
    "Department": "HR"
  }
}
```

**Comment by sathishkumarkaliavaradhan-okta** [comment]
Thanks again @rossgrambo ,

I want to use the preview version but not sure about the provider. currently, I am supporting loading the flag from appsettings.json for development otherwise it fetches from the server directly.  can this preview version work for our use case?

Thanks,
Sathishkumar

**Comment by sathishkumarkaliavaradhan-okta** [comment]
Thank you so much @rossgrambo,

Since I am using the dotnet provider, can't use the preview version. I will wait for the release happens.

Thanks,
Sathishkumar

**Comment by sathishkumarkaliavaradhan-okta** [comment]
Hi @rossgrambo ,
Good Morning
Do you have any timeline? when will the new release which includes RequirementType: All 
Thanks,
Sathishkumar

**Comment by rossgrambo** [comment]
We're aiming to do a preview release for the Provider soon, likely sometime next week to support RequirementType. The stable versions won't be released until the portal updates are done, and I don't have a good timeline for that yet.

**Comment by zhiyuanliang-ms** [comment]
Hi, @sathishkumarkaliavaradhan-okta 
If you are using our portal, there is a bug of setting "RequirementType" in "Advanced Edit", which is mentioned in issue #257. You may need to wait for our next new release. (hopefully, in a month)
Sorry for the inconvenience.

**Comment by zhenlan** [comment]
Close as dup of #257
