### ISSUE TITLE
FeatureFilter not found exception

### ISSUE THREAD

**Issue by sathishkumarkaliavaradhan-okta** [microsoft/FeatureManagement-Dotnet#235]
Hi @rossgrambo, @jimmyca15 

I have registered the custom filter for one of the features like the code below

`// Initialize Feature Management
var serviceCollection = new ServiceCollection();
serviceCollection.AddSingleton<IConfiguration>(configuration)
                 .AddFeatureManagement()
                 .AddFeatureFilter<DeviceFilter>();`

and have other features which require the target filter which I didn't register the filter so I got the below exception

`The feature filter 'Microsoft.Targeting' specified for feature 'device_health_enabled2' was not found.`

Then I added PercentageFilter and TargetingFilter in the code below

// Initialize Feature Management
var serviceCollection = new ServiceCollection();
serviceCollection.AddSingleton<IConfiguration>(configuration)
                 .AddFeatureManagement()
                 .AddFeatureFilter<PercentageFilter>()
                 .AddFeatureFilter<TargetingFilter>()
                 .AddFeatureFilter<DeviceFilter>();

Now I am getting the below exception

Unable to resolve service for type 'Microsoft.FeatureManagement.FeatureFilters.ITargetingContextAccessor' while attempting to activate 'Microsoft.FeatureManagement.FeatureFilters.TargetingFilter'.

Could you please help me resolve the above exception?

Also, I would like to register the ignore missing filter option but couldn't find a way to do it. I am using the dependency injection in the WPF client application
https://github.com/microsoft/FeatureManagement-Dotnet#missing-feature-filters

Thanks,
Sathishkumar

**Comment by rossgrambo** [comment]
Hello @sathishkumarkaliavaradhan-okta!

For the exception, try using ContextualTargetingFilter instead. Meaning try changing this:
```
.AddFeatureFilter(TargetingFilter)
```
to
```
.AddFeatureFilter(ContextualTargetingFilter)
```

For the ignore missing filters option, our tests usually separate it from the other singleton adding. Not sure if it matters, too much but try this:
```
var serviceCollection = new ServiceCollection();
serviceCollection
    .Configure<FeatureManagementOptions>(options =>
    {
        options.IgnoreMissingFeatureFilters = true;
    });

serviceCollection.AddSingleton(config)
  .AddFeatureManagement()
  ...
```

Hope these help! Let me know if you still have issues.

**Comment by sathishkumarkaliavaradhan-okta** [comment]
Hi @rossgrambo ,

Thank you so much for your quick answer, it's working fine.

I have added the filters below.

 serviceCollection.AddSingleton<IConfiguration>(configuration)
                .AddFeatureManagement()
                .AddFeatureFilter<PercentageFilter>()
                .AddFeatureFilter<ContextualTargetingFilter>()
                .AddFeatureFilter<DeviceFilter>();
do I still need PercentageFilter needs to be added or ContextualTargetingFilter will take care of both targeting and percentage?

Thanks,
Sathishkumar

**Comment by rossgrambo** [comment]
Happy to hear!

I'm assuming that you don't also need the Percentage filter, as ContextualTargetingFilter handles percents via the "RolloutPercentage" fields. But I'll give a more thorough answer-

It depends what your filters look like. If you're only using a targeting filter / all of your percentages are within the `"Name": "Targeting"` filter, then the contextual targeting filter is all you need. 

If you also declared a `"Name": "Percentage"` filter- you would also need to add that filter as well. 

Alternatively, you could also set `IgnoreMissingFeatureFilters` to `false` (Or omit the option entirely) and then evaluate your filter. It will raise an exception if you declared a Percentage Filter but didn't `.AddFeatureFilter(` it.

**Comment by sathishkumarkaliavaradhan-okta** [comment]
Thank you so much @rossgrambo .
I just removed the Percentage filter and tested with percentage and it works fine.
Thank you so much for your timely answers.

Thanks,
Sathishkumar
