### ISSUE TITLE
is SDK cache persisted? 

### ISSUE THREAD

**Issue by sathishkumarkaliavaradhan** [microsoft/FeatureManagement-Dotnet#255]
Using the below code to cache the feature flag value in our console app

`// To connect with feature flag CDN edge.
options.Connect(this.oktaVerifyFeatureProviderConfiguration.RemoteConfigurationConnectionString);
options.UseFeatureFlags(configure
    => configure.CacheExpirationInterval
        = TimeSpan.FromMinutes(this.oktaVerifyFeatureProviderConfiguration.RemoteConfigurationCacheExpiration));`

when I restart the app, the value does not persist in SDK at all instead it makes a call to the server to download the configuration. is it expected?

**Comment by sathishkumarkaliavaradhan** [comment]
Hi @rossgrambo ,

Good Morning.

do you have any update the on above question? like I would like to persist the value locally so that when the client WPF app close and opens again it retains the value otherwise before I close the app feature flag was on and after reopens it's on by default unless the network calls made and get the latest value.

Thanks,
Sathishkumar

**Comment by jimmyca15** [comment]
@sathishkumarkaliavaradhan 

There is no local (disk) persisted cache. Restarting the application means the library would need to contact the server to pull feature flag values.
