### ISSUE TITLE
Log level for missing feature declarations.

### ISSUE THREAD

**Issue by eldola-norsea** [microsoft/FeatureManagement-Dotnet#265]
When a feature declaration is not found, a warning message is logged: "The feature declaration for the feature '{feature}' was not found." For our use case, missing feature declarations in production is the expected behavior, and should not be logged as a warning, but rather as 'debug' or 'info'.

Suggestion: Lower the log level to debug or info, or add an option MissingFeaturesLogLevel to specify the log level.

**Comment by jimmyca15** [comment]
@rossgrambo In this scenario feature flags are defined lazily (post-deployment). It's a valid scenario, and unfortunately we are polluting logs in this invalid scenario. I think we will want to reduce this log to debug. Really, that's what it is. Debug information that can help pinpoint the fact that you may have missed defining a flag.

**Comment by rossgrambo** [comment]
Adjusted in https://github.com/microsoft/FeatureManagement-Dotnet/pull/283
