### ISSUE TITLE
Adding version of public interface with generic parameters 

### ISSUE THREAD

**Issue by brental** [microsoft/FeatureManagement-Dotnet#268]
The docs recommend defining feature flags as an enum and then normally using nameof when consuming them. The FeatureGateAttribute also supports passing feature flags as objects as an alternative to using nameof. Now that C# supports generic attributes would consideration be given to adding generic versions of the public interface members to allow consuming the library without having to use nameof or pass feature flags as objects? These generic versions would allow specifying an enum type for the feature flags and then accept feature flag parameters of that enum type rather than strings.

I currently maintain the following library that extends Microsoft.FeatureManagement for this but thought it could be a useful addition to these libraries themselves:
https://github.com/TFeatureManagement/TFeatureManagement

There would still be a few limitations to this as currently AspNetCore does not support generic tag helpers (at least not using them directly - they can be used as a base class). However, most of the public members could have generic versions of them added.

**Comment by jimmyca15** [comment]
The docs need an update in this regard. This should no longer be considered the recommended approach. Using type names as string placeholders can lead to issues due to code refactoring which is a natural part of the evolution of a code base.

As such, const string should be preferred instead of passing an enum to provide a feature flag name.

**Comment by jimmyca15** [comment]
@brental

Right, the docs should be updated to avoid usage of enum and recommend using const strings.

**Comment by brental** [comment]
Raised #269 to cover updates to docs and closing this.
