### ISSUE TITLE
Update docs with latest recommendations for defining and consuming feature flags

### ISSUE THREAD

**Issue by brental** [microsoft/FeatureManagement-Dotnet#269]
In [this comment](https://github.com/microsoft/FeatureManagement-Dotnet/issues/268#issuecomment-1743344584) it is stated that the recommended approach for defining and consuming feature flags is no longer to use an enum. Instead, it is recommended to use constants and that the docs need to be updated to reflect this. So, this issue is to get the docs updated with the new recommended approach.

**Comment by jimmyca15** [comment]
Updated. Rather than us making a recommendation we have just replaced the references in documentation to string literals.

Thanks for bringing this to our attention.

**Comment by brental** [comment]
Thanks @jimmyca15 @zhiyuanliang-ms, just using strings without a recommendation makes sense. 

However, I did find that there is still one place in the docs where nameof is still used which is in the section on the tag helper. That should probably be updated to just use a string as well?

**Comment by zhiyuanliang-ms** [comment]
@brental Thank you for catching it. That's a mistake.
