### ISSUE TITLE
Should the single-value parameters (on Feature Filters) be serialized as arrays ?

### ISSUE THREAD

**Issue by celer1tas** [microsoft/FeatureManagement-Dotnet#27]
In Azure App Configuration, when defining a feature with a feature filter that has one parameter then that parameter is serialized as single-value.

```
public class BrowserPreviewFeatureFilterParameters
{
        public IList<string> Allowed { get; set; } = new List<string>();
        public IList<string> Blocked { get; set; } = new List<string>();
}

```
In the below example if we use the above model for deserialization then the parameter "Allowed" is deserialized but "Blocked" is not.
![image](https://user-images.githubusercontent.com/5678736/69825240-7decdc00-1206-11ea-9686-aea6279c3ecd.png)

Observations:
- This means that if someone defines the same parameter twice in Azure portal then the developer must deserialize field as an array, if the parameter is defined only once then the developer needs to deserialize the value using a completely different model: 

```
public class BrowserPreviewFeatureFilterParameters
{
        public IList<string> Allowed { get; set; } = new List<string>();
        public string Blocked { get; set; } ;
}

```
**ISSUE:** The developer has to implement a JSONConverter to handle both scenarios, which is not nice. 
Is this something that can be improved from Azure App Configuration portal UI ?

**Comment by celer1tas** [comment]
Is there an easy/recommended way to avoid the above easy when configuring the "AllowedBrowsers" parameter in Azure App Configure, as per this example: [https://github.com/microsoft/FeatureManagement-Dotnet/blob/master/examples/FeatureFlagDemo/appsettings.json](url) ? 

```
"Home": true,
    "Beta": {
      "EnabledFor": [
        {
          "Name": "Browser",
          "Parameters": { // This json object maps to a strongly typed configuration class
            "AllowedBrowsers": [ "Chrome", "Edge" ]
          }
        }
      ]
    }
```

**Comment by jimmyca15** [comment]
Related to https://github.com/Azure/AppConfiguration/issues/147. The only way to avoid this before we revamp this UI to have more intuitive support for arrays is to suffix the array element with it's position in the array.

E.g.
Allowed:0 Chrome
Allowed:1 Edge

It is on our to-do list to make this more user friendly. At this point it's very hard to work with arrays like this since managing indexes is a lot of overhead.

**Comment by jimmyca15** [comment]
Arrays are supported now. https://github.com/Azure/AppConfiguration/issues/147
