### ISSUE TITLE
Performance over head for feature management filter

### ISSUE THREAD

**Issue by justConfused** [microsoft/FeatureManagement-Dotnet#286]
Hi Team,

Is there a place I can understand the over head of using feature management backed with appsetting only. Does it increase request by millisecond or increase memory? 

Is there any comparison or any documentation?

**Comment by jimmyca15** [comment]
@justconfused

> of using feature management backed with appsetting only

Are you asking for a comparison against reading feature flags from Azure App Configuration? If so, there is no performance or memory consumption differences.
