### ISSUE TITLE
Change the feature flag name reference to const string

### ISSUE THREAD

**Issue by zhiyuanliang-ms** [microsoft/FeatureManagement-Dotnet#291]
Currently, our testcases are using `Enum.GetName(typeof(Features), Features.TargetingTestFeature)` to reference a feature flag.

**Comment by zhiyuanliang-ms** [comment]
FeatureFlagDemo should also be updated.

**Comment by juniwang** [comment]
Could you explain what's wrong with name reference? 

Also, I'm aslo wondering why not just use `nameof`? For example, `nameof(Features.TargetingTestFeature)`, which sounds pretty simple and straightforward.

**Comment by zhiyuanliang-ms** [comment]
@juniwang The context is here: #268  #269 
Jimmy and I discussed this offline. We prefered to use const string. There was also a PR to update the README: https://github.com/microsoft/FeatureManagement-Dotnet/pull/275
