### ISSUE TITLE
ValueTask returns

### ISSUE THREAD

**Issue by amis92** [microsoft/FeatureManagement-Dotnet#292]
Has it been maybe considered (for v3) to migrate all async APIs from Task-returns to ValueTask returns?

I have not measured the performance, but when initially assessing usability of this library, it struck me as a possible pain point. For services we're creating, that have hundreds RPSs, allocation is an important factor. The FeatureManagement APIs are async to allow possible async implementations but the base scenario of a simple sync code using configuration values would seem like a very quick and non-allocating scenario. This library, by using Task returns, already ensures at least a couple of allocations for what could potentially be a simple lookup/comparison operation. In terms of possible drawbacks - results can't be awaited multiple times or blocked-on, but the current set of SDK-provided analyzers is guarding that, and the core scenario - checking a flag - doesn't lend to being awaited multiple-times, at least from a design point of view.

Seeing as you're already committed to breaking changes (CancellationTokens, yay!), I'd like to ask you to consider such an improvement as well. Thanks!

**Comment by jimmyca15** [comment]
@amis92

V3 won't have breaking changes. Instead there is a new interface, [IVariantFeatureManager](https://github.com/microsoft/FeatureManagement-Dotnet/blob/197c32506abe81a87613162ae9c1199c57db1e1d/src/Microsoft.FeatureManagement/IVariantFeatureManager.cs#L14). This will return ValueTask.

New usage can use IVariantManager to get cancellation token support as well as utilize [feature variants](https://github.com/microsoft/FeatureManagement-Dotnet/tree/preview#variants).

**Comment by jimmyca15** [comment]
By the way I notice IVariantManager is incorrectly using Task instead of ValueTask in current code.

cc @rossgrambo

**Comment by amis92** [comment]
Hmm. A bit problematic then, to drive allocation-less effort, because only top level is possible, and dependencies like IFeatureDefinitionProvider cannot be changed.

Completely unrelated, but I think cancelation tokens should have a default value in the interface methods. , so callers who don't care don't have to pass an empty token. An example: [IHealthCheck](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.diagnostics.healthchecks.ihealthcheck.checkhealthasync?view=dotnet-plat-ext-7.0#microsoft-extensions-diagnostics-healthchecks-ihealthcheck-checkhealthasync(microsoft-extensions-diagnostics-healthchecks-healthcheckcontext-system-threading-cancellationtoken))

**Comment by jimmyca15** [comment]
@amis92 if we do decide to take a breaking change in the future we will not hesitate to go ValueTask all the way down. For now, without the break this is where we land.

**Comment by amis92** [comment]
Sure. I didn't see it was just the variant api

**Comment by rossgrambo** [comment]
Closing this for now- We've changed all Tasks to ValueTasks that are not breaking changes. In the future when we do a breaking change release- we will change the rest of them.
