### ISSUE TITLE
CUD-Support from Code

### ISSUE THREAD

**Issue by JuliusMikkela** [microsoft/FeatureManagement-Dotnet#301]
Hello, real sorry if this is documented somewhere and I've just missed it, but I was wondering if it's possible to Create/Update/Delete Feature Flags from code? Native Azure App Configuration has support to mod the configs from code via Azure.Data.AppConfiguration, like:

```csharp        
var client = new ConfigurationClient("MyConnectionString");
var setting = new ConfigurationSetting("MyKey", "MyValue");
await client.SetConfigurationSettingAsync(setting);
```
But try as I might, I haven't found an equivalent for Feature Flags. Does it exist and I've just missed it - or doesn't it and if so why?

**Comment by zhenlan** [comment]
@JuliusMikkela hope this helps
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample9_FeatureFlags.md

**Comment by jimmyca15** [comment]
Hello @JuliusMikkela I think Zhenlan's reply answers the question. Let me know if that's not the case.

**Comment by JuliusMikkela** [comment]
Hi, yes that's exactly what I was looking for, thank you!
