### ISSUE TITLE
Support for Code-first Configuration (builder)

### ISSUE THREAD

**Issue by mike7ang1rdz** [microsoft/FeatureManagement-Dotnet#323]
I would like to package my features within the dll  without   JSON to avoid modifications when we distribute the dll (package).

ideally using a builder 

thanks

**Comment by jimmyca15** [comment]
@mike7ang1rdz

are you able to provide an example of what type of code you are looking to be able to write. Even if pseudo-code. Ideally it can help seed the conversation and make sure we're accomplishing what you're looking for.

**Comment by mike7ang1rdz** [comment]
Sure.

Serilog is a great example

1. You can build an instance using a builder:

```
using var log = new LoggerConfiguration()
    .WriteTo.Console()
    .WriteTo.File("log.txt")
    .CreateLogger();

```
2. Or creating an instance reading from appsettings.json
```

{
  "Serilog": {
    "Using":  [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      { "Name": "Console" },
      { "Name": "File", "Args": { "path": "Logs/log.txt" } }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    "Destructure": [
      { "Name": "With", "Args": { "policy": "Sample.CustomPolicy, Sample" } },
      { "Name": "ToMaximumDepth", "Args": { "maximumDestructuringDepth": 4 } },
      { "Name": "ToMaximumStringLength", "Args": { "maximumStringLength": 100 } },
      { "Name": "ToMaximumCollectionCount", "Args": { "maximumCollectionCount": 10 } }
    ],
    "Properties": {
        "Application": "Sample"
    }
  }
}
```

https://github.com/serilog/serilog-settings-configuration

**Comment by zhiyuanliang-ms** [comment]
@mike7ang1rdz 
The FeatureManagement is built on the IConfiguration. After release 3.1.0, FeatureManager and ConfigurationFeatureDefintionProvider are exposed to public. You can use it directly without DI.

I am digesting your request. If my understanding is correct, for your case, the feature flag will be hard coded.
You can create IConfiguration like this [ref](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration#configure-console-apps)

**Comment by jimmyca15** [comment]
Hello @mike7ang1rdz, does the approach that @zhiyuanliang-ms suggested work for your scenario?

**Comment by mike7ang1rdz** [comment]
It works perfectly thanks.

**Comment by jimmyca15** [comment]
> You can use them directly without DI.

To expand upon what @zhiyuanliang-ms mentioned, this approach can also be used when FeatureManager is in .NET core's DI container. Just make sure to add the in-memory collection to the main configuration that is also added to DI.
