### ISSUE TITLE
Should we have a feature flag schema specification?

### ISSUE THREAD

**Issue by zhiyuanliang-ms** [microsoft/FeatureManagement-Dotnet#358]
Something like this: https://github.com/Azure/AppConfiguration/blob/main/docs/FeatureManagement/FeatureFlag.v2.0.0.schema.json

**Comment by rossgrambo** [comment]
I think you just linked to it- meaning we do have a feature flag specification 😄. It's just not in this repo- which I think makes sense because it's for more languages than .net.

**Comment by jimmyca15** [comment]
Yes we should.
