### ISSUE TITLE
Is the "xunit.assert" dependency a mistake?

### ISSUE THREAD

**Issue by fubar-coder** [microsoft/FeatureManagement-Dotnet#360]
Hi,

I was wondering, whether the "xunit.assert" dependency of the "4.0.0-preview" was a mistake? Will this dependency kept for the release or is it a preview-only thing?

The reason why I'm asking this, is that it was my expectation, that "xunit" packages only appear in unit test projects.

**Comment by jimmyca15** [comment]
Absolutely a mistake, thank you for bringing this to attention !

@zhiyuanliang-ms

**Comment by zhiyuanliang-ms** [comment]
@jimmyca15 The PR is sent out.

**Comment by zhiyuanliang-ms** [comment]
Update: PR merged.
