### ISSUE TITLE
How to combine FeatureFlags settings from multiple providers / sources?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/FeatureManagement-Dotnet#37]
_Cross-post from https://github.com/Azure/AppConfiguration/issues/228 since it is relevant to both `Microsoft.FeatureManagement` and `Azure App Configuration`._

Suppose that I want to do the following:
- use Azure App Configuration to set Feature Flags
  - for the production environment
  - as a baseline for the development environment
- have a way for locally overriding the Feature Flags in the development environment, e.g. using cookies

The usecase for this is e.g. for testers / product owners to switch on/off Features when checking their behavior or presenting them, without needing access to Azure and without impacting others members of the development team.
Another use case could be for users opting in to preview features.

The documentation explains how to add Azure App Configuration as a source for FeatureManagement. I assume I would need to implement an `IFeatureFilter` or an `ISessionManager` to provide the values from the cookies, but I don't see this documented.

I believe an `IFeatureFilter` should be able to independently provide a Feature value, so how can we set what source gets preference over the other? The comparison cannot be done inside the `IFeatureFilter` I believe. 

The logic I want to achieve is this:

| Azure App Configuration feature state | Local (cookie-based?) feature value | Calculated feature result |
|---|---|---|
| **`false`** | `null` | **`false`** |
| **`true`** | `null` | **`true`** |
| `false` | **`false`** | **`false`** |
| `true` | **`false`** | **`false`** |
| `false` | **`true`** | **`true`** |
| `true` | **`true`** | **`true`** |

**Comment by hansmbakker** [comment]
For now we decided to not use (cookie) overrides in our production environment. However it would be still a good thing to document I think.

**Comment by jimmyca15** [comment]
`ISessionManager` provides a way to short circuit feature filter evaluation for a feature flag and provide the result of whether a feature should be enabled. If you're cookies contain the state of whether a feature should be enabled or disabled then using an `ISessionManager` implementation which pulls from the HTTP session (cookie) makes perfect sense. If the session manager can't provide the value the feature management system falls back to evaluating the state of the feature based off the configuration of the application. In your case that would mean falling back to Azure App Configuration. It's the behavior you're looking for.

You mentioned that a feature filter should also be able to do this and that is also correct. Either way of accomplishing this could be done. If you use a feature filter you could have a `CookieCacheFilter` feature filter.

```
"FeatureManagement":
{
  "Beta": {
    "EnabledFor": [
       "CookieCache": {
         "Parameters":" {
           "Default": false/true
         }
       }
    ]
  }
}
```

The intent of the filter that I mocked up above would be
1. Check feature state from http session (cookie).
2. If feature state not present, use "Default" parameter as the result of whether the feature should be on off. The default parameter would come from the configuration of the application (Azure App Configuration).

**Comment by hansmbakker** [comment]
Thank you! That looks good.

I understand this repo is about the feature management NuGet and not the Azure App Configuration product, but it would be nice if the solution would integrate well in the Feature Manager screen of Azure App Configuration.

They have a screen with on/off switches but those switches won’t work as defaults if the value needs to end up in the filter configuration. So I believe the solution you proposed using the `ISessionManager` would be good!

**Comment by jimmyca15** [comment]
The Azure App Configuration team is the team that owns this package and we appreciate the feedback. The `ISessionManager` should serve your purpose well.

The feature filter interface is being revamped, but it is possible to accomplish what you mentioned today. Set the feature flag state to conditional by adding a feature filter. If you were to use the one I mocked you would name it "CookieCache". This has to match the name of the filter in your application. Then you can set the `Default` parameter that I added.

Here's a pic of me setting it up.

![image](https://user-images.githubusercontent.com/21000428/71200464-186c9800-2266-11ea-8520-abd6590ff3fc.png)

**Comment by hansmbakker** [comment]
Yes, I agree it can work by editing the filter parameters, I just liked the really clear on/off switches :)

Thank you for your explanation! It helps a lot!
