### ISSUE TITLE
async implementation of TryGetAsync on ISessionManager not possible?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/FeatureManagement-Dotnet#38]
The `ISessionManager` interface switched to using an `async` approach, which is good in itself.

However the TryGetAsync function uses an `out` parameter which forbids declaring the function as `async` - so you cannot `await` `Task`s in the function body.

This feels a bit awkward - do you have any example on how to best tackle that?

**Comment by jimmyca15** [comment]
This is definitely a problem and needs to be addressed in the next release. An oversight in the transition to async.
