### ISSUE TITLE
Package dependency: Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore

### ISSUE THREAD

**Issue by zhenlan** [microsoft/FeatureManagement-Dotnet#390]
The pacakge 
- `Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore` 

does not depend on the package 
- `Microsoft.FeatureManagement.Telemetry.ApplicationInsights`

This forces users to add both packages individually. I understand there is no code dependency between them but is there a scenario where `Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore` is useful by itself? Should we make the AspNetCore one pull the other one automatically?

**Comment by jimmyca15** [comment]
Let's update it.
