### ISSUE TITLE
Namespace of ApplicationInsightsTelemetryPublisher

### ISSUE THREAD

**Issue by zhenlan** [microsoft/FeatureManagement-Dotnet#392]
The namespace of `ApplicationInsightsTelemetryPublisher` is **Microsoft.FeatureManagement.Telemetry.ApplicationInsights** today. It's cumbersome for users to add long namespaces like this. I'd propose we move it under **Microsoft.FeatureManagement.Telemetry**. In the future, if we add any new publishers, we can put them all under the same namespace. This way users don't have to add namespaces for each publisher individually.

**Comment by jimmyca15** [comment]
Sounds reasonable. Will be more discoverable. Shouldn't cause bloat since a user would have to specifically target this package to have this type appear.

**Comment by rossgrambo** [comment]
To clarify- we're just changing the namespace and not the package name- correct? Meaning in the future we would have two packages:

1. `Microsoft.FeatureManagement.Telemetry.ApplicationInsights`
2. `Microsoft.FeatureManagement.Telemetry.LogAnalytics`

Both having:
```csharp
namespace Microsoft.FeatureManagement.Telemetry;
```

Additionally, how do we feel about `Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore` ? It holds the `TargetingTelemetryInitializer`. 

Should it follow suit and be:
```csharp
namespace Microsoft.FeatureManagement.Telemetry.AspNetCore;
```
?

**Comment by jimmyca15** [comment]
> Additionally, how do we feel about Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore ? It holds the TargetingTelemetryInitializer

I don't think it should change. Here's why. The publisher is an implementation of a generic concept. Any telemetry destination would need it's own publisher. So standardizing to simple namespace allows the implementations to be discoverable easy as Zhenlan mentioned.

But, ITelemetryInitializers are App Insights specific components. I don't think they generalize well.

**Comment by rossgrambo** [comment]
Makes sense. Updated PR.
