### ISSUE TITLE
Are you planning releasing a final version of this package soon?

### ISSUE THREAD

**Issue by zepedrosilva** [microsoft/FeatureManagement-Dotnet#40]
I am very keen to use this package, but I would prefer to use a non-preview version of it and I have been waiting since version 1.0-preview for one. Are there any plans on releasing one?

**Comment by mariotee** [comment]
they addressed something here: https://github.com/microsoft/FeatureManagement-Dotnet/issues/10

it seems like when that Azure thing goes live, this will go with it. not sure.

**Comment by zhenlan** [comment]
Yes, we do plan to release a stable version soon aligned with the Azure App Configuration GA.
