### ISSUE TITLE
Include Targeting Information on outgoing telemetry

### ISSUE THREAD

**Issue by rossgrambo** [microsoft/FeatureManagement-Dotnet#409]
Outgoing telemetry relied on some ambient property (like App Insights' User field) to connect published events to metrics. We should specifically use the UserId field used on the TargetingContext and name it more specifically 'TargetingId', since this can be used to target things besides users.

**Comment by jimmyca15** [comment]
Is there a PR that addressed this issue?

**Comment by rossgrambo** [comment]
Yes - https://github.com/microsoft/FeatureManagement-Dotnet/pull/347
