### ISSUE TITLE
Guidance for Azure Functions

### ISSUE THREAD

**Issue by wahyuen** [microsoft/FeatureManagement-Dotnet#41]
Hi,

We are currently interested in using the Feature Management services in our Azure Functions. We've figured out how to register the service and can connect to the App Configuration instance to resolve the state of the FeatureFlag, however, we weren't sure how the 'refresh' of the feature flag is supposed to work?

My current tests show that toggling the feature flag from enabled/disabled doesn't affect the result of 
`await _featureManager.IsEnabledAsync("TestFlag")` and only seems to take effect upon function restart. 

cheers

**Comment by calloncampbell** [comment]
Hi @wahyuen, you might want to take a look at using Azure App Configuration which is a service to centrally manage application settings and feature flags and is perfect for Azure Functions. 

It's currently in preview and is free for the time being.

Take a look at how to use it with Azure Functions:
https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-azure-functions-csharp

**Comment by wahyuen** [comment]
@calloncampbell to clarify, we are already using Azure App Configuration. What we are seeking is how to get Feature Flags to be 'refreshed' on the fly as in a standard WebAPI application but in Azure Functions. The registration process is slightly different with how the DI pipelines are injected within Functions and there doesn't seem to be any documentation (that I can find) to illustrate how one might update Feature Flags and have them propagate to Functions without issuing a restart of the whole App Service.

**Comment by zhenlan** [comment]
Hi @wahyuen, please see Jimmy's [comment](https://github.com/Azure/AppConfiguration/issues/249#issuecomment-577931286) on the same topic. You can also find an example code snippet of using feature management in Azure Functions with DI [here](https://github.com/Azure/AppConfiguration/issues/252).

**Comment by jimmyca15** [comment]
@wahyuen please let me know if Zhenlan's answer did not solve the issue. Thanks!
