### ISSUE TITLE
Consider moving `TargetingHttpContextMiddleware` to the App Insights package

### ISSUE THREAD

**Issue by rossgrambo** [microsoft/FeatureManagement-Dotnet#424]
We could move `TargetingHttpContextMiddleware` to the same package as `TargetingTelemetryInitializer`. The `TargetingHttpContextMiddleware` is not intended to be used without the `TargetingTelemetryInitializer`.

**Comment by jimmyca15** [comment]
If we do that, I'd like to see the library expose an 

`AddXyz`

and 

`UseXyz` pattern.

**Comment by jimmyca15** [comment]
I imagine that taking this change would result in changes in https://github.com/microsoft/FeatureManagement-Dotnet/pull/416

**Comment by rossgrambo** [comment]
The middleware has been reworked to use Activity, which is no longer specific to App Insights. Leaving in the AspNetCore package now makes sense.
