### ISSUE TITLE
Why Microsoft.FeatureManagement.FeatureFilters project is empty?

### ISSUE THREAD

**Issue by ardacetinkaya** [microsoft/FeatureManagement-Dotnet#43]
I guess, it would be nice if filters are moved into the Microsoft.FeatureManagement.FeatureFilters.

Any specific reason for that?

And also any guidance or ideas to have some base filter? I am using Time Window approach for all my other filters as all feature flags have time based life-time.

It would be nice to have these because I don't want to use modified version of this project any more...

Maybe I'll send some PR 🙃

**Comment by jimmyca15** [comment]
The Microsoft.FeatureManagement.FeatureFilters project should be removed. It was never used. There are two feature filters included in the `Microsoft.FeatureManagement` package.

* PercentageFilter
* TimeWindowFilter

There is no base filter since there isn't much to share.
