### ISSUE TITLE
Logging hook?

### ISSUE THREAD

**Issue by jonathh21** [microsoft/FeatureManagement-Dotnet#44]
Hi, are there any hooks for logging?

It'd be super awesome if there was a to log all the features that are 'known about' and what they status is, including on a refresh.

Anyone know of a way?

**Comment by jimmyca15** [comment]
Hard to understand exactly what it is you're trying to log but it sounds like the state of the features. This will be possible for all features after this issue is resolved. https://github.com/microsoft/FeatureManagement-Dotnet/issues/29

**Comment by jimmyca15** [comment]
Haven't heard any updates. Please re-open if the question is not resolved.
