### ISSUE TITLE
Add a link to preview on main readme

### ISSUE THREAD

**Issue by rossgrambo** [microsoft/FeatureManagement-Dotnet#442]
Sometimes developers land on our main branch but are looking for preview documentation. We should make it easy for them to route themselves.

**Comment by zhiyuanliang-ms** [comment]
Our new [doc](https://learn.microsoft.com/en-us/azure/azure-app-configuration/feature-management-dotnet-reference?pivots=stable-version) has a pivot selector to let reader switch between stable and preview version. So I think this issue can be closed.
