### ISSUE TITLE
Cannot use the TargetingFilter in .NET class library project

### ISSUE THREAD

**Issue by bdscarboro1** [microsoft/FeatureManagement-Dotnet#446]
FeatureManagementBuilder is internal, so cannot instantiate from a class library project, which in turn means cannot do the equivalent of this setup from a web api project:
`builder.Services.AddFeatureManagement()
    .WithTargeting<HttpContextTargetingContextAccessor>();`

Are there code samples anywhere on how to use Microsoft.FeatureManagement from a class library?

**Comment by zhiyuanliang-ms** [comment]
Hi, @bdscarboro1 

Start from Microsoft.FeatureManagement v3.1.0, `FeatureManager and `ConfigurationFeatureDefniitonProvider` are exposed to public. Also, all built-in feature filters (targeting, timewindow, percentage) are public class. 

We just released v3.3.0, where we made parameters of the constructors of the built-in feature filters mentioned above optional. This change is mainly for improving the experience of non-DI usage of feature management library.

So, I would suggest you update to the latest Microsoft.FeatureManagement v3.3.0.

There are two targeting filters in this lib, [`ContextualTargetingFilter`](https://github.com/microsoft/FeatureManagement-Dotnet?tab=readme-ov-file#targeting-in-a-console-application) and `[TargetingFilter`](https://github.com/microsoft/FeatureManagement-Dotnet?tab=readme-ov-file#targeting-in-a-web-application).

They are respectively designed for console app(explicit `TargetingContext`) and web app(ambient `TargetingContext` through `ITargetingContextAccessor`).

For more details, please read [Targeting](https://github.com/microsoft/FeatureManagement-Dotnet?tab=readme-ov-file#targeting).

Here is an example of how to use feature management without dependency injection.

``` C#
using Microsoft.Extensions.Configuration;
using Microsoft.FeatureManagement;
using Microsoft.FeatureManagement.FeatureFilters;

IConfiguration configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();

IFeatureDefinitionProvider featureDefinitionProvider = new ConfigurationFeatureDefinitionProvider(configuration);

IFeatureManager featureManager = new FeatureManager(featureDefinitionProvider)
{
    FeatureFilters = new List<IFeatureFilterMetadata> { new ContextualTargetingFilter() }
};

var targetingContext = new TargetingContext()
{
    UserId = "Jeff"
};

bool res = await featureManager.IsEnabledAsync("MyFeature", targetingContext);
```

**Comment by zhiyuanliang-ms** [comment]
@bdscarboro1 Does this example help you?

**Comment by bdscarboro1** [comment]
Yes, it did help me, thank you!
