### ISSUE TITLE
Consider using `TimeProvider` using Microsoft.Bcl.TimeProvider nuget package

### ISSUE THREAD

**Issue by JakeYallop** [microsoft/FeatureManagement-Dotnet#451]
There is a comment in `ISystemClock` here:
https://github.com/microsoft/FeatureManagement-Dotnet/blob/31b0efcd8c51d355c1a45a6ca98b483fd71f3f74/src/Microsoft.FeatureManagement/FeatureFilters/ISystemClock.cs#L9-L18

However this is not correct. The runtime provides a down-level package https://www.nuget.org/packages/Microsoft.Bcl.TimeProvider/ that allows `TimeProvider` to be used code using older versions of the runtime, or code that needs to support .NET standard.

**Comment by zhiyuanliang-ms** [comment]
@JakeYallop Thank you very much for paying attention to the latest changes in our repo.

This was a oversight. I didn't know there is `Microsoft.Bcl.TimeProvider`.

 I have sent out a PR to update it. #452

**Comment by zhiyuanliang-ms** [comment]
The PR #452 will reference a new package. We plan to adopt this change with the next major version bump because introducing a new package might lead to potential breaking changes.
