### ISSUE TITLE
Consider making IFeatureSettingsProvider public

### ISSUE THREAD

**Issue by pardahlman** [microsoft/FeatureManagement-Dotnet#46]
There are many system in the wild that uses other feature toggling frameworks that does not load its data from `IConfiguration`, nor has a data source that can be used as a ConfigurationProvider. The idea behind making `IFeatureSettingsProvider` public is that these systems could use a custom implementation as part of their migration story over to this toggle framework.

**Comment by slomangino123** [comment]
Looking into a way to feature flag api endpoints easily I stumbled across the same issue as @pardahlman. As such we are looking for a way to toggle feature flags without using IConfiguration but rather a third party service. Being able to provide a decorated IFeatureSettingsProvider would allow sourcing feature flags from anywhere.

**Comment by JosephWoodward** [comment]
Came here to say the same thing. It'd be great to be able to use this library for more than `IConfiguration` based datasources. Making this interface public would enable that.

**Comment by jimmyca15** [comment]
This has been added in [the latest release](https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.2.0-preview).
