### ISSUE TITLE
Version 3.5.0 release notes

### ISSUE THREAD

**Issue by pascalberger** [microsoft/FeatureManagement-Dotnet#479]
There was recently https://www.nuget.org/packages/Microsoft.FeatureManagement/3.5.0 published to nuget.org, but latest release / tag on this repository is still 3.4.0.

Can you please provide a changelog and provide a way for consumers to check from which commit a release was created.

**Comment by jimmyca15** [comment]
@pascalberger 

Thanks for reaching out. I have just created release 3.5.0 https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/3.5.0

@zhiyuanliang-ms will fill out the release information for the 4.x-preview release that was also released.

**Comment by zhiyuanliang-ms** [comment]
Hi, @pascalberger  
Sorry for the delay of release note. I was waiting for this [PR](https://github.com/Azure/AppConfiguration/pull/943) to be merged. We will also have release note in the Azure App Config central repo.

I have created the [release note](https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/4.0.0-preview4) for 4.x-preview. Its content might be a bit rough. I will update the content, once the PR mention aboved is finalized.
