### ISSUE TITLE
question: Is it supported on net framework 4.8 and web.config?

### ISSUE THREAD

**Issue by aberbegall** [microsoft/FeatureManagement-Dotnet#511]
Is it supported on net framework 4.8 project with web.config?

**Comment by zhiyuanliang-ms** [comment]
Hi, @aberbegall I think so. Since we are targeted on netstandard. Did you meet any specific problem while using this library in your .net framework project?

**Comment by aberbegall** [comment]
@zhiyuanliang-ms thanks for your reply. My main is problem is how to set it up. I can add the nugget package but I am struggling to register the FeatureManager service with unity and how specify to the feature in the web.config as I do in appsettings.json... best would be to find an example or any code tip, many thanks

**Comment by zhiyuanliang-ms** [comment]
@aberbegall 

Feature management is built on the .net configuration system. Here is our [doc](https://learn.microsoft.com/en-us/azure/azure-app-configuration/feature-management-dotnet-reference?pivots=preview-version#feature-flag-configuration). Anyway, you need a `IConfiguration` as the feature flag source.

**Comment by aberbegall** [comment]
@zhiyuanliang-ms thanks for the links and tips... 
I have a ASP.NET MVC project with Startup.cs with Owin and Unity IoC and the web.config required for the IIS app setup. 

I hold plenty of web app settings in the web.config and I need to keep them there, cannot be migrated to appsettings.

I will examine the given links and see any possibilities to keep my web.config and sort out the Feature Flag declaration.

**Comment by rossgrambo** [comment]
Closing this for now
