### ISSUE TITLE
Provide for Distributed Systems

### ISSUE THREAD

**Issue by udlose** [microsoft/FeatureManagement-Dotnet#57]
**Feature Request:**
Based on documentation and blog articles I've read and from poking around some of the source code, the FeatureManagement system appears to be a wrapper on top of the Configuration System.  The Configuration System doesn't easily provide for setting up a configuration source that is distributed - e.g. Database, Distributed Cache, etc.

**Question:**
Is there a recommendation for accomplishing this? I would expect this to be something that is easily configurable thru the Feature Management API but I must be missing something.

**Comment by JosephWoodward** [comment]
It sounds like this is somewhat related to [this question](https://github.com/microsoft/FeatureManagement-Dotnet/issues/46).

**Comment by NicolasReyDotNet** [comment]
I have the exact same point, so I started to store my FeatureManagement json in a distributed system (Hashicorp Vault) instead of in a local Appsettings files, but I don't know how to refresh any changes.
I've just asked the [question](https://github.com/microsoft/FeatureManagement-Dotnet/issues/65).

**Comment by udlose** [comment]
IMO, this is a configuration that should be available thru FeatureManagement without having to write custom code for this type of usage scenario.

**Comment by JosephWoodward** [comment]
@udlose Agreed, hopefully the team will consider #46 and make it possible. 🤞

**Comment by udlose** [comment]
> @udlose Agreed, hopefully the team will consider #46 and make it possible. 🤞

@JosephWoodward  The diffierence between #46 and this issue is that I'm asking for this functionality to be "built-in" to FeatureManagement so that I don't have to use `IFeatureSettingsProvider` to do a custom implementation myself.  There should be a "plug-n-play" configuration where we tell FeatureManagement where to look for the settings based on some defined interface, and then it handles the "monitoring, polling, etc." to look for changes and update itself accordingly.

Cloud-based solutions are so ubiquitous now that it's shocking that there isn't a solution here for distributed settings storage.

**Comment by wapplegate** [comment]
So it looks like there is a PR for #46 it would be great if it could be merged and released soon.

**Comment by jimmyca15** [comment]
This has been added in [the latest release](https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.2.0-preview).

**Comment by NicolasREY69330** [comment]
@jimmyca15 
Great news! Will you update the doc providing some samples?

**Comment by jimmyca15** [comment]
@NicolasREY69330 

Hey Nicolas, when you mention "the doc" I think you mean the README. Let me know if you meant another doc.

The README was updated to discuss [custom feature providers](https://github.com/microsoft/FeatureManagement-Dotnet#custom-feature-providers).

The tests have a sample custom feature provider.
[InMemoryFeaureDefinitionProvider](https://github.com/microsoft/FeatureManagement-Dotnet/blob/d91bf9da0ef7224263714c460b0e0ca2ab02b322/tests/Tests.FeatureManagement/InMemoryFeatureDefinitionProvider.cs#L9)
[Usage](https://github.com/microsoft/FeatureManagement-Dotnet/blob/d91bf9da0ef7224263714c460b0e0ca2ab02b322/tests/Tests.FeatureManagement/FeatureManagement.cs#L488)

**Comment by NicolasREY69330** [comment]
@jimmyca15 
Yes ! My bad I didn't see you had already updated the readme.
Great work !
