### ISSUE TITLE
Provide support for .Net Framework and other technologies

### ISSUE THREAD

**Issue by Joe-U-Questionmark** [microsoft/FeatureManagement-Dotnet#58]
@jimmyca15  

Are there plans to support clients for non .NET Core apps? i.e .Net Framework and PHP?

**Comment by jimmyca15** [comment]
.NET Framework can use this library already since it is .NET Standard. There are no plans to support PHP with this library.

**Comment by jimmyca15** [comment]
The console app example would be similar to how an `IFeatureManager` would be obtained in a .NET Framework application: https://github.com/microsoft/FeatureManagement-Dotnet/blob/master/examples/ConsoleApp/Program.cs

**Comment by jimmyca15** [comment]
Please re-open if there are more questions.

**Comment by Joe-U-Questionmark** [comment]
@jimmyca15 slightly off topic from this SDK but is their a REST API we could use to build a similar implementation in PHP?

**Comment by zhenlan** [comment]
@Joe-U-Questionmark this library does not depend on any services. It read feature flags all from `IConfiguration`. 

People can build any configuration providers to feed feature flags into `IConfiguration`. The [Azure App Configuration](https://aka.ms/AzureAppConfiguration) has a config provider (in .NET and Java) to do so. If you are interested to read feature flags from the App Configuration in PHP, then yes, the App Configuration has [REST APIs](https://github.com/Azure/AppConfiguration#rest-api-reference).
