### ISSUE TITLE
Dynamic change a Feature and apply it at runtime without restarting the application

### ISSUE THREAD

**Issue by NicolasReyDotNet** [microsoft/FeatureManagement-Dotnet#65]
Hi,

I can't find any answer on all docs I've read so far, so here is my point :

_The context :_
I feed the `IConfiguration` object using the `IConfigurationBuilder ` with an external ressource (Hashicorp Vault here), I don't work with the Appsettings file but with a Inmemory configuration provider (`builder.AddInMemoryCollection`) feed by my Json from Hashicorp .
It works well, and the `services.AddFeatureManagement()` allows me to use the `IFeatureManager` as expected for example.

_My point :_
I would like to dynamically change some feature toogle:
for example enable **FeatureA** which was previously disabled, or disable **FeatureB** which was previously enabled. It's easy to change my Json in HaschiCorp and implement a kind of polling to Hashicorp to get keep my features activation up to date. **But I don't want to have to restart the application to get the new changes**.

Is there any way to achieve this ? ie force the FeatureManagement lib to "update its information" during runtime ?
Or could we update the `IConfiguration` at runtime ? If yes the FeatureManagement will be updated as expected ?

Thank you for your help.

**Comment by jimmyca15** [comment]
@NicolasReyDotNet the feature manager uses the [`IConfiguration`'s reload token](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationroot.getreloadtoken?view=dotnet-plat-ext-3.1) to detect when there are changes. 

It sounds like you are using an in-memory provider for IConfiguration. That may not have any mechanism to trigger reload. You may have to [do it manually](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationroot.reload?view=dotnet-plat-ext-3.1)

**Comment by udlose** [comment]
> It sounds like you are using an in-memory provider for IConfiguration. That may not have any mechanism to trigger reload. You may have to [do it manually](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationroot.reload?view=dotnet-plat-ext-3.1)

The site for Hashicorp Vault shows that this is an external, out-of-process distributed provider - not in-memory.

**Comment by NicolasReyDotNet** [comment]
@jimmyca15 

Ok I understand, I'll follow the path of creating a personalized ConfigurationProvider handling hotreload.
Thanks

**Comment by NicolasReyDotNet** [comment]
@jimmyca15 
Just to complete the discussion : I've implemented my own Configuration provider (replacing the InMemory configuration provider) that handles reload, and which triggers the `OnReload` method (explicitly called, it's mandatory) on feeding my data from Hashicorp Vault, it then notify the FeatureManagement as expected, my Features are updated in iConfuration and in FeatureManagement as well without any reboot.

Thanks for your help

**Comment by udlose** [comment]
@NicolasReyDotNet how did you implement the configuration provider?  Do you mind sharing the source?  I'm wondering if you're polling to detect changes since the configuration values are out-of-process.  TIA.

**Comment by NicolasReyDotNet** [comment]
@udlose Well here is [detailed article](https://ofpinewood.com/blog/creating-a-custom-configurationprovider-for-a-entity-framework-core-source) I followed to implement my own configuration provider, it's really clear and well explained. 

For loading new values, currenlty I make an explicit call to a controller action that triggers the update of secrets from Hashicorp Vault using an event, but yes I intend to make a background service that will poll the external service, just like Microsoft does with [Azure App Configuration](https://docs.microsoft.com/fr-fr/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core3x#reload-data-from-app-configuration) but I don't use a sentinel just like themn, I use the version of each secret to determine which one should be replaced, this is an inbound feature of [Hashicorp Vault client library](https://github.com/rajanadar/VaultSharp).
By the way I'm going to check if there isn't any webhook that Hashicorp Vault may trigger on secret change, to avoid polling.

Feel free to come back to me if you need.
