### ISSUE TITLE
Consider moving to Microsoft.Extensions.FeatureManagement

### ISSUE THREAD

**Issue by TheBlueSky** [microsoft/FeatureManagement-Dotnet#7]
Consider changing the namespaces and the assembly name to be `Microsoft.Extensions.FeatureManagement`. IMO, this makes the library look more like the rest of .NET Core "standard" libraries than a stand-alone thing.

Besides, it has the same "spirit" that other `Microsoft.Extensions.*` libraries have.

**Comment by jimmyca15** [comment]
Thanks for the feedback @TheBlueSky. This is something the team considered early on and it turned out extensions is not the best namespace for this project. It's a good proposal though, just didn't seem to fit.
