### ISSUE TITLE
Asp.net Core web app doesn't throw any exception when feature flag free quota limit is reached

### ISSUE THREAD

**Issue by SailleshPawar** [microsoft/FeatureManagement-Dotnet#70]
This is something that we faced in production recently. 
Accidentlally we were using Free tier of App Configuration in production workload for our web app. 
We were deploying the new changes in the production environment and we were getting 500.30 service unavailable error, when we were trying to access the API's
We tried running the command **dotnet *.dll** from kudu using dotnet .dll command and it just hangs doesn't show any error in console. 
At last we tested on local env and found it was due to feature flag free quota limit is reached application was not running and no exception was shown in console, making it hard to understand what is the root cause of the issue.

below is our code for program.cs

`{

                     var builtConfig = builder.Build();

                     var azureServiceTokenProvider = new AzureServiceTokenProvider();

                     var keyVaultClient = new KeyVaultClient(
                         new KeyVaultClient.AuthenticationCallback(
                             azureServiceTokenProvider.KeyVaultTokenCallback));

                     builder.AddAzureKeyVault(
                         $"https://{builtConfig["KeyVaultName"]}.vault.azure.net/",
                         keyVaultClient,
                         new DefaultKeyVaultSecretManager());

                 })

                .ConfigureAppConfiguration((ctx, builder) =>
                {
                    var builtConfig = builder.Build();
                    builder.AddAzureAppConfiguration(options => {
                        options.Connect(builtConfig["feature-flag-connection-string"])
                            .UseFeatureFlags();
                    });
                })`

**Comment by jimmyca15** [comment]
Hello @sailleshPawar, this issue is for the Azure App Configuration provider for .NET Core. I have moved the issue there: https://github.com/Azure/AppConfiguration-DotnetProvider/issues/170
