### ISSUE TITLE
create sample for Blazor WASM usage

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/FeatureManagement-Dotnet#76]
I'm trying to use the feature management within BlazorWASM, however have been unable to get this to work; I'm unable to see any exceptions of why this is the case; please consider providing support/examples of how to use this library from a BlazorWASM application

**Comment by unaizorrilla** [comment]
Probably you can move and use https://github.com/xabaril/Esquio and enjoy!

**Comment by zhiyuanliang-ms** [comment]
Hi, @grahamehorner 
So far, the Blazor WASM is not a targeting scenario of FeatureManagement. We are investigating how to support Blazor Server app.
https://github.com/microsoft/FeatureManagement-Dotnet/issues/206#issuecomment-1754848575

**Comment by zhiyuanliang-ms** [comment]
@grahamehorner  I created an example in this PR #306  to demonstrate how to use FeatureManagement in Blazor server app. Hope it can help.

**Comment by zhiyuanliang-ms** [comment]
@grahamehorner The example of Blazor server app can be found here: https://github.com/microsoft/FeatureManagement-Dotnet/tree/main/examples/BlazorServerApp

**Comment by zhiyuanliang-ms** [comment]
Feel free to reopen this issue if you need more help on how to use Feature Management in Blazor. @grahamehorner
