### ISSUE TITLE
Feature names with colon in name are not parsed correctly

### ISSUE THREAD

**Issue by peterwurzinger** [microsoft/FeatureManagement-Dotnet#90]
Given the following configuration:
```json
"FeatureManagement": {
    "Feature1": true,
    "Prefix:Feature2": true
}
```
Querying the features was a bit surprising at first:
```cs
featureManager.IsEnabledAsync("Feature1") //returns true
featureManager.IsEnabledAsync("Prefix:Feature2") //returns false
```
Listing the feature names is also quite misleading:
```cs
featureManager.GetFeatureNamesAsync(); //returns "Feature1", "Prefix"
```

By taking a closer look, the colon is of course not only a gimmick, but more like a common separator for config sections. So when using the JSON file provider, the abovementioned configuration could also be semantically identical rephrased as
```json
"FeatureManagement": {
    "Feature1": true,
    "Prefix": {
        "Feature2": true
    }
}
```
And that explains the weird behavior.

To solve that, would it be a possible to tokenize given feature names by `:` , treating them as config-sections and only the last segment as the name? Imho that would fix the `"Prefix":Feature" : true` case, as well as enable feature grouping (see above).

**Comment by jimmyca15** [comment]
In general, the ':' character should be avoided in setting names in json settings files in .NET Core. The ':' character is treated specially as you have called out. I don't think it would be a good idea to go against that concept. It may be a good idea to call this out in the readme though.

**Comment by peterwurzinger** [comment]
Well, since `IsEnabledAsync("Prefix:Feature")` will **never** behave as expected, would it then be an option to throw an exception, if the input string contains a colon?

**Comment by jimmyca15** [comment]
That's a great suggestion. Technically if someone is using a custom `IFeatureDefinitionProvider` then colon might be fine for them, but if the default `ConfigurationFeatureDefinitionProvider` is being used then we can throw an `ArgumentException` to prevent confusion in a case like this.

**Comment by zhiyuanliang-ms** [comment]
https://github.com/microsoft/FeatureManagement-Dotnet/pull/288
Resolved.
