### ISSUE TITLE
Turning off the internal cache within UseFeatureFlags(), or overarching AddAzureAppConfiguration method

### ISSUE THREAD

**Issue by JakeRoper4** [microsoft/FeatureManagement-Dotnet#94]
Hello,

We're currently in the process of wrapping our feature flag code into an API, which surfaces the values stored in AAC out in an easy to read way for our clients/ui's to consume. We have written some Specflow API tests that covers all the scenarios that we may find our API's being used for, but we have come across a situation that seems to have us stumped. 

What we do in said tests, is that we clear the AAC (**Azure App Configuration**) down, to remove any existing feature flags from any past test runs to avoid any interference between runs. 

For example:

We create the following features `Feature1-1`, `Feature2-1` using the AAC SDK.
We then poll our API, which calls the `GetFeatureNamesAsync` method. This returns:

```
Feature1-1
Feature2-1 
```

We loop through the features returned above, and check to see if they're enabled or not, via use of a custom feature filter, which when complete, is then sent as a response from the API.
We assert based on the response given in the test, and check that the values retrieved are correct.

However, if we run these tests as a group, one after another, we're finding that some of the tests fail, as they're getting some of the old test run features within their response. 

From what I can gather, the API is updating its AAC configuration provider every 30 seconds or so, as that is what the default cache expiration value is. However, is there perhaps a way that we can get the provider to be updated/refreshed PER REQUEST? Or per call to `GetFeaturesNamesAsync`? 

I know that we can update the cache value to within a second, as that's the minimum value. But is there a way that we can perhaps turn off the caching provided by the packages? As we're relying on using our own caching layer within the API for limiting calls to AAC where possible.

**Comment by jimmyca15** [comment]
This behavior boils down to the AAC provider as you are aware. Today, we released [version 4.0.0](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/4.0.0) ([ASP.NetCore Middleware Package](https://www.nuget.org/packages/Microsoft.Azure.AppConfiguration.AspNetCore/4.0.0)) of the configuration provider. This exposes [`IConfigurationRefresher.SetDirty(TimeSpan? maxDelay)`](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/b6b9a7261c0826d4689c37042a0a67ef039a7e04/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationRefresher.cs#L37). You can call this API whenever to invalidate the cache on demand.

Let me know if this helps or if you need more info.

**Comment by JakeRoper4** [comment]
Thanks for the reply @jimmyca15. That does help. I'll be sure to update the AppConfiguration package and see if this helps. However, is there any way that you can turn off the provider cache at all? I'm wary of how many requests that are made towards my Azure App Configuration instances at the moment, so would like to know if the above query is possible.

**Comment by jimmyca15** [comment]
@JakeRoper4 there is no way to turn off the caching.

**Comment by jimmyca15** [comment]
Looks like questions were answered. Please feel free to re-open or file an other issue if needed.
