### ISSUE TITLE
Unable to create both IFeatureFilter and IContextualFeatureFilter with same FilterAlias.

### ISSUE THREAD

**Issue by aforank** [microsoft/FeatureManagement-Dotnet#98]
When I create an implementation for both `IFeatureFilter` and `IContextualFeatureFilter` with same `FilterAlias`. I get the below exception 

`Multiple feature filters match the configured filter named` 

**Use case**
I created two feature filter with same filter alias as follows

```csharp
[FilterAlias("CompanyFilter")]
public class HttpCompanyFilter : IFeatureFilter
{
	public Task<bool> EvaluateAsync(FeatureFilterEvaluationContext context)
	{
		// Return flag based on http context;
	}
}
```

```csharp
[FilterAlias("CompanyFilter")]
public class CompanyContextFilter : IContextualFeatureFilter<CompanyContext>
{
	public Task<bool> EvaluateAsync(FeatureFilterEvaluationContext featureFilterContext, CompanyContext companyContext)
	{
		// Return flag based on CompanyContext parameter;
	}
}
```

In some situations where I know that HTTP context will always be available, I want to call the feature manager without passing any context. This should call a filter which implements `IFeatureFilter`

```csharp
await featureFlagManager.IsEnabledAsync("FeatureA");
```

However, in some cases, I do not have the HTTP context available, so I would like to call the feature manager by passing the app context this time. This should call a filter which implements `IContextualFeatureFilter<CompanyContext>`

```csharp
var context = new CompanyContext()
{
 Code = "SomeValue"
};

await featureFlagManager.IsEnabledAsync("FeatureA", context);
```

I also tried to create a single filter implementing both `IFeatureFilter` and `IContextualFeatureFilter`but apparently this is also not allowed by the framework.

**Comment by jimmyca15** [comment]
Thanks for reporting this @aforank, it is indeed not supported at the moment. It looks like you have a valid scenario for this and we can look into adding support for it. 

In the meantime the only way to do this is to have two different filters with two different aliases. Unfortunately, as I'm sure you're trying to prevent, you will have to list both of the filters with the same settings for each feature that you want to use them.

**Comment by zhiyuanliang-ms** [comment]
Hi @aforank
I will take this issue. This will be resolved in the next release.

**Comment by jimmyca15** [comment]
Now possible with the release of 3.0
